const verbs = [
  { base: "Begin",  past: "began"   },
  { base: "Break",  past: "broke"   },
  { base: "Bring",  past: "brought" },
  { base: "Build",  past: "built"   },
  { base: "Buy",    past: "bought"  },
  { base: "Catch",  past: "caught"  },
  { base: "Come",   past: "came"    },
  { base: "Do",     past: "did"     },
  { base: "Drink",  past: "drank"   },
  { base: "Eat",    past: "ate"     },
  { base: "Fall",   past: "fell"    },
  { base: "Find",   past: "found"   },
  { base: "Fly",    past: "flew"    },
  { base: "Forget", past: "forgot"  },
  { base: "Get",    past: "got"     },
  { base: "Give",   past: "gave"    },
  { base: "Go",     past: "went"    },
  { base: "Have",   past: "had"     },
  { base: "Hear",   past: "heard"   },
  { base: "Know",   past: "knew"    },
  { base: "Leave",  past: "left"    },
  { base: "Lose",   past: "lost"    },
  { base: "Make",   past: "made"    },
  { base: "Meet",   past: "met"     },
  { base: "Pay",    past: "paid"    },
  { base: "Put",    past: "put"     },
  { base: "Read",   past: "read",   note: "spelling stays the same, but pronunciation changes: /riːd/ → /rɛd/" },
  { base: "Ring",   past: "rang"    },
  { base: "Say",    past: "said"    },
  { base: "See",    past: "saw"     },
  { base: "Sell",   past: "sold"    },
  { base: "Sit",    past: "sat"     },
  { base: "Sleep",  past: "slept"   },
  { base: "Speak",  past: "spoke"   },
  { base: "Stand",  past: "stood"   },
  { base: "Take",   past: "took"    },
  { base: "Tell",   past: "told"    },
  { base: "Think",  past: "thought" },
  { base: "Win",    past: "won"     },
  { base: "Write",  past: "wrote"   },
];

module.exports = verbs;
