const words = [
   { "id": 1, "type": "verb", "en": "handle", "hy": ["կառավարել", "հաղթահարել"] },
  { "id": 2, "type": "verb", "en": "manage", "hy": ["կառավարել"] },
  { "id": 3, "type": "verb", "en": "improve", "hy": ["բարելավել"] },
  { "id": 4, "type": "verb", "en": "increase", "hy": ["ավելացնել"] },
  { "id": 5, "type": "verb", "en": "reduce", "hy": ["նվազեցնել"] },
  { "id": 6, "type": "verb", "en": "solve", "hy": ["լուծել"] },
  { "id": 7, "type": "verb", "en": "fix", "hy": ["ուղղել"] },
  { "id": 8, "type": "verb", "en": "check", "hy": ["ստուգել"] },
  { "id": 9, "type": "verb", "en": "test", "hy": ["փորձարկել"] },
  { "id": 10, "type": "verb", "en": "review", "hy": ["վերանայել"] },

  { "id": 11, "type": "verb", "en": "update", "hy": ["թարմացնել"] },
  { "id": 12, "type": "verb", "en": "upgrade", "hy": ["բարելավել"] },
  { "id": 13, "type": "verb", "en": "create", "hy": ["ստեղծել"] },
  { "id": 14, "type": "verb", "en": "build", "hy": ["կառուցել"] },
  { "id": 15, "type": "verb", "en": "develop", "hy": ["զարգացնել"] },
  { "id": 16, "type": "verb", "en": "design", "hy": ["նախագծել"] },
  { "id": 17, "type": "verb", "en": "plan", "hy": ["պլանավորել"] },
  { "id": 18, "type": "verb", "en": "organize", "hy": ["կազմակերպել"] },
  { "id": 19, "type": "verb", "en": "prepare", "hy": ["պատրաստել"] },
  { "id": 20, "type": "verb", "en": "arrange", "hy": ["կազմակերպել"] },

  { "id": 21, "type": "verb", "en": "start", "hy": ["սկսել"] },
  { "id": 22, "type": "verb", "en": "stop", "hy": ["կանգնեցնել"] },
  { "id": 23, "type": "verb", "en": "continue", "hy": ["շարունակել"] },
  { "id": 24, "type": "verb", "en": "finish", "hy": ["ավարտել"] },
  { "id": 25, "type": "verb", "en": "complete", "hy": ["ավարտել"] },
  { "id": 26, "type": "verb", "en": "cancel", "hy": ["չեղարկել"] },
  { "id": 27, "type": "verb", "en": "delay", "hy": ["ուշացնել"] },
  { "id": 28, "type": "verb", "en": "postpone", "hy": ["հետաձգել"] },
  { "id": 29, "type": "verb", "en": "schedule", "hy": ["պլանավորել"] },
  { "id": 30, "type": "verb", "en": "reschedule", "hy": ["վերապլանավորել"] },

  { "id": 31, "type": "verb", "en": "discuss", "hy": ["քննարկել"] },
  { "id": 32, "type": "verb", "en": "explain", "hy": ["բացատրել"] },
  { "id": 33, "type": "verb", "en": "describe", "hy": ["նկարագրել"] },
  { "id": 34, "type": "verb", "en": "clarify", "hy": ["պարզաբանել"] },
  { "id": 35, "type": "verb", "en": "mention", "hy": ["նշել"] },
  { "id": 36, "type": "verb", "en": "confirm", "hy": ["հաստատել"] },
  { "id": 37, "type": "verb", "en": "deny", "hy": ["մերժել"] },
  { "id": 38, "type": "verb", "en": "agree", "hy": ["համաձայնել"] },
  { "id": 39, "type": "verb", "en": "disagree", "hy": ["չհամաձայնել"] },
  { "id": 40, "type": "verb", "en": "suggest", "hy": ["առաջարկել"] },

  { "id": 41, "type": "verb", "en": "recommend", "hy": ["խորհուրդ տալ"] },
  { "id": 42, "type": "verb", "en": "advise", "hy": ["խորհուրդ տալ"] },
  { "id": 43, "type": "verb", "en": "request", "hy": ["պահանջել"] },
  { "id": 44, "type": "verb", "en": "respond", "hy": ["պատասխանել"] },
  { "id": 45, "type": "verb", "en": "reply", "hy": ["պատասխանել"] },
  { "id": 46, "type": "verb", "en": "contact", "hy": ["կապվել"] },
  { "id": 47, "type": "verb", "en": "call", "hy": ["զանգել"] },
  { "id": 48, "type": "verb", "en": "message", "hy": ["հաղորդագրություն ուղարկել"] },
  { "id": 49, "type": "verb", "en": "send", "hy": ["ուղարկել"] },
  { "id": 50, "type": "verb", "en": "receive", "hy": ["ստանալ"] },

  { "id": 51, "type": "verb", "en": "deliver", "hy": ["առաքել"] },
  { "id": 52, "type": "verb", "en": "provide", "hy": ["տրամադրել"] },
  { "id": 53, "type": "verb", "en": "supply", "hy": ["մատակարարել"] },
  { "id": 54, "type": "verb", "en": "offer", "hy": ["առաջարկել"] },
  { "id": 55, "type": "verb", "en": "accept", "hy": ["ընդունել"] },
  { "id": 56, "type": "verb", "en": "reject", "hy": ["մերժել"] },
  { "id": 57, "type": "verb", "en": "approve", "hy": ["հաստատել"] },
  { "id": 58, "type": "verb", "en": "support", "hy": ["աջակցել"] },
  { "id": 59, "type": "verb", "en": "assist", "hy": ["օգնել"] },
  { "id": 60, "type": "verb", "en": "help", "hy": ["օգնել"] },

  { "id": 61, "type": "verb", "en": "deal with", "hy": ["զբաղվել"] },
  { "id": 62, "type": "verb", "en": "handle with", "hy": ["վարվել"] },
  { "id": 63, "type": "verb", "en": "work on", "hy": ["աշխատել"] },
  { "id": 64, "type": "verb", "en": "focus on", "hy": ["կենտրոնանալ"] },
  { "id": 65, "type": "verb", "en": "depend on", "hy": ["կախված լինել"] },
  { "id": 66, "type": "verb", "en": "belong to", "hy": ["պատկանել"] },
  { "id": 67, "type": "verb", "en": "look for", "hy": ["փնտրել"] },
  { "id": 68, "type": "verb", "en": "find out", "hy": ["պարզել"] },
  { "id": 69, "type": "verb", "en": "figure out", "hy": ["հասկանալ"] },
  { "id": 70, "type": "verb", "en": "carry out", "hy": ["կատարել"] },

  { "id": 71, "type": "verb", "en": "set up", "hy": ["կարգավորել"] },
  { "id": 72, "type": "verb", "en": "turn on", "hy": ["միացնել"] },
  { "id": 73, "type": "verb", "en": "turn off", "hy": ["անջատել"] },
  { "id": 74, "type": "verb", "en": "log in", "hy": ["մուտք գործել"] },
  { "id": 75, "type": "verb", "en": "log out", "hy": ["դուրս գալ"] },
  { "id": 76, "type": "verb", "en": "sign in", "hy": ["մուտք գործել"] },
  { "id": 77, "type": "verb", "en": "sign up", "hy": ["գրանցվել"] },
  { "id": 78, "type": "verb", "en": "fill in", "hy": ["լրացնել"] },
  { "id": 79, "type": "verb", "en": "take over", "hy": ["վերցնել"] },
  { "id": 80, "type": "verb", "en": "go on", "hy": ["շարունակել"] },

  { "id": 81, "type": "verb", "en": "bring up", "hy": ["բարձրացնել թեմա"] },
  { "id": 82, "type": "verb", "en": "point out", "hy": ["նշել"] },
  { "id": 83, "type": "verb", "en": "check out", "hy": ["ստուգել"] },
  { "id": 84, "type": "verb", "en": "look into", "hy": ["ուսումնասիրել"] },
  { "id": 85, "type": "verb", "en": "take part", "hy": ["մասնակցել"] },
  { "id": 86, "type": "verb", "en": "give up", "hy": ["հանձնվել"] },
  { "id": 87, "type": "verb", "en": "keep on", "hy": ["շարունակել"] },
  { "id": 88, "type": "verb", "en": "carry on", "hy": ["շարունակել"] },
  { "id": 89, "type": "verb", "en": "end up", "hy": ["ավարտվել"] },
  { "id": 90, "type": "verb", "en": "come up", "hy": ["առաջանալ"] },

  { "id": 91, "type": "verb", "en": "run into", "hy": ["հանդիպել"] },
  { "id": 92, "type": "verb", "en": "deal with", "hy": ["զբաղվել"] },
  { "id": 93, "type": "verb", "en": "bring back", "hy": ["վերադարձնել"] },
  { "id": 94, "type": "verb", "en": "put off", "hy": ["հետաձգել"] },
  { "id": 95, "type": "verb", "en": "take off", "hy": ["հանել"] },
  { "id": 96, "type": "verb", "en": "turn up", "hy": ["հայտնվել"] },
  { "id": 97, "type": "verb", "en": "turn down", "hy": ["մերժել"] },
  { "id": 98, "type": "verb", "en": "set off", "hy": ["մեկնել"] },
  { "id": 99, "type": "verb", "en": "break down", "hy": ["խափանվել"] },
  { "id": 100, "type": "verb", "en": "pick up", "hy": ["վերցնել"] },
  { "id": 101, "type": "verb", "en": "analyze", "hy": ["վերլուծել"] },
  { "id": 102, "type": "verb", "en": "evaluate", "hy": ["գնահատել"] },
  { "id": 103, "type": "verb", "en": "estimate", "hy": ["գնահատել"] },
  { "id": 104, "type": "verb", "en": "calculate", "hy": ["հաշվել"] },
  { "id": 105, "type": "verb", "en": "measure", "hy": ["չափել"] },
  { "id": 106, "type": "verb", "en": "compare", "hy": ["համեմատել"] },
  { "id": 107, "type": "verb", "en": "contrast", "hy": ["համադրել"] },
  { "id": 108, "type": "verb", "en": "identify", "hy": ["նույնականացնել"] },
  { "id": 109, "type": "verb", "en": "recognize", "hy": ["ճանաչել"] },
  { "id": 110, "type": "verb", "en": "determine", "hy": ["որոշել"] },

  { "id": 111, "type": "verb", "en": "define", "hy": ["սահմանել"] },
  { "id": 112, "type": "verb", "en": "outline", "hy": ["ներկայացնել ընդհանուր"] },
  { "id": 113, "type": "verb", "en": "summarize", "hy": ["ամփոփել"] },
  { "id": 114, "type": "verb", "en": "report", "hy": ["զեկուցել"] },
  { "id": 115, "type": "verb", "en": "present", "hy": ["ներկայացնել"] },
  { "id": 116, "type": "verb", "en": "demonstrate", "hy": ["ցուցադրել"] },
  { "id": 117, "type": "verb", "en": "illustrate", "hy": ["պատկերել"] },
  { "id": 118, "type": "verb", "en": "highlight", "hy": ["ընդգծել"] },
  { "id": 119, "type": "verb", "en": "emphasize", "hy": ["շեշտադրել"] },
  { "id": 120, "type": "verb", "en": "mention", "hy": ["նշել"] },

  { "id": 121, "type": "verb", "en": "note", "hy": ["նշել"] },
  { "id": 122, "type": "verb", "en": "record", "hy": ["գրանցել"] },
  { "id": 123, "type": "verb", "en": "track", "hy": ["հետևել"] },
  { "id": 124, "type": "verb", "en": "monitor", "hy": ["վերահսկել"] },
  { "id": 125, "type": "verb", "en": "observe", "hy": ["դիտարկել"] },
  { "id": 126, "type": "verb", "en": "review", "hy": ["վերանայել"] },
  { "id": 127, "type": "verb", "en": "inspect", "hy": ["զննել"] },
  { "id": 128, "type": "verb", "en": "examine", "hy": ["ուսումնասիրել"] },
  { "id": 129, "type": "verb", "en": "assess", "hy": ["գնահատել"] },
  { "id": 130, "type": "verb", "en": "verify", "hy": ["ստուգել"] },

  { "id": 131, "type": "verb", "en": "validate", "hy": ["վավերացնել"] },
  { "id": 132, "type": "verb", "en": "approve", "hy": ["հաստատել"] },
  { "id": 133, "type": "verb", "en": "authorize", "hy": ["թույլատրել"] },
  { "id": 134, "type": "verb", "en": "reject", "hy": ["մերժել"] },
  { "id": 135, "type": "verb", "en": "decline", "hy": ["մերժել"] },
  { "id": 136, "type": "verb", "en": "accept", "hy": ["ընդունել"] },
  { "id": 137, "type": "verb", "en": "consider", "hy": ["քննարկել"] },
  { "id": 138, "type": "verb", "en": "review again", "hy": ["վերանայել կրկին"] },
  { "id": 139, "type": "verb", "en": "double-check", "hy": ["կրկնակի ստուգել"] },
  { "id": 140, "type": "verb", "en": "recheck", "hy": ["վերստուգել"] },

  { "id": 141, "type": "verb", "en": "improve on", "hy": ["բարելավել"] },
  { "id": 142, "type": "verb", "en": "work with", "hy": ["աշխատել"] },
  { "id": 143, "type": "verb", "en": "collaborate", "hy": ["համագործակցել"] },
  { "id": 144, "type": "verb", "en": "coordinate", "hy": ["համակարգել"] },
  { "id": 145, "type": "verb", "en": "communicate", "hy": ["հաղորդակցվել"] },
  { "id": 146, "type": "verb", "en": "negotiate", "hy": ["բանակցել"] },
  { "id": 147, "type": "verb", "en": "discuss further", "hy": ["քննարկել ավելի"] },
  { "id": 148, "type": "verb", "en": "clarify further", "hy": ["պարզաբանել ավելի"] },
  { "id": 149, "type": "verb", "en": "follow up", "hy": ["հետևել"] },
  { "id": 150, "type": "verb", "en": "reach out", "hy": ["կապ հաստատել"] },

  { "id": 151, "type": "verb", "en": "notify", "hy": ["տեղեկացնել"] },
  { "id": 152, "type": "verb", "en": "inform", "hy": ["տեղեկացնել"] },
  { "id": 153, "type": "verb", "en": "announce", "hy": ["հայտարարել"] },
  { "id": 154, "type": "verb", "en": "update on", "hy": ["թարմացնել"] },
  { "id": 155, "type": "verb", "en": "keep updated", "hy": ["տեղեկացնել"] },
  { "id": 156, "type": "verb", "en": "remind", "hy": ["հիշեցնել"] },
  { "id": 157, "type": "verb", "en": "warn", "hy": ["զգուշացնել"] },
  { "id": 158, "type": "verb", "en": "alert", "hy": ["զգուշացնել"] },
  { "id": 159, "type": "verb", "en": "advise on", "hy": ["խորհուրդ տալ"] },
  { "id": 160, "type": "verb", "en": "consult", "hy": ["խորհրդակցել"] },

  { "id": 161, "type": "verb", "en": "support with", "hy": ["աջակցել"] },
  { "id": 162, "type": "verb", "en": "assist with", "hy": ["օգնել"] },
  { "id": 163, "type": "verb", "en": "guide", "hy": ["ուղղորդել"] },
  { "id": 164, "type": "verb", "en": "train", "hy": ["վարժեցնել"] },
  { "id": 165, "type": "verb", "en": "teach", "hy": ["սովորեցնել"] },
  { "id": 166, "type": "verb", "en": "learn from", "hy": ["սովորել"] },
  { "id": 167, "type": "verb", "en": "gain", "hy": ["ստանալ"] },
  { "id": 168, "type": "verb", "en": "achieve", "hy": ["հասնել"] },
  { "id": 169, "type": "verb", "en": "reach", "hy": ["հասնել"] },
  { "id": 170, "type": "verb", "en": "meet (goal)", "hy": ["հասնել"] },

  { "id": 171, "type": "verb", "en": "fail", "hy": ["ձախողվել"] },
  { "id": 172, "type": "verb", "en": "succeed", "hy": ["հաջողվել"] },
  { "id": 173, "type": "verb", "en": "improve performance", "hy": ["բարելավել կատարողականություն"] },
  { "id": 174, "type": "verb", "en": "increase efficiency", "hy": ["ավելացնել արդյունավետություն"] },
  { "id": 175, "type": "verb", "en": "reduce cost", "hy": ["նվազեցնել արժեք"] },
  { "id": 176, "type": "verb", "en": "optimize", "hy": ["օպտիմիզացնել"] },
  { "id": 177, "type": "verb", "en": "simplify", "hy": ["պարզեցնել"] },
  { "id": 178, "type": "verb", "en": "complicate", "hy": ["բարդացնել"] },
  { "id": 179, "type": "verb", "en": "adjust", "hy": ["կարգավորել"] },
  { "id": 180, "type": "verb", "en": "adapt", "hy": ["հարմարվել"] },

  { "id": 181, "type": "verb", "en": "modify", "hy": ["փոփոխել"] },
  { "id": 182, "type": "verb", "en": "edit", "hy": ["խմբագրել"] },
  { "id": 183, "type": "verb", "en": "revise", "hy": ["վերանայել"] },
  { "id": 184, "type": "verb", "en": "replace", "hy": ["փոխարինել"] },
  { "id": 185, "type": "verb", "en": "remove", "hy": ["հեռացնել"] },
  { "id": 186, "type": "verb", "en": "add", "hy": ["ավելացնել"] },
  { "id": 187, "type": "verb", "en": "include", "hy": ["ներառել"] },
  { "id": 188, "type": "verb", "en": "exclude", "hy": ["բացառել"] },
  { "id": 189, "type": "verb", "en": "combine", "hy": ["միավորել"] },
  { "id": 190, "type": "verb", "en": "separate", "hy": ["բաժանել"] },

  { "id": 191, "type": "verb", "en": "divide", "hy": ["բաժանել"] },
  { "id": 192, "type": "verb", "en": "connect", "hy": ["միացնել"] },
  { "id": 193, "type": "verb", "en": "disconnect", "hy": ["անջատել"] },
  { "id": 194, "type": "verb", "en": "link", "hy": ["կապել"] },
  { "id": 195, "type": "verb", "en": "attach", "hy": ["կցել"] },
  { "id": 196, "type": "verb", "en": "detach", "hy": ["անջատել"] },
  { "id": 197, "type": "verb", "en": "upload", "hy": ["բեռնել"] },
  { "id": 198, "type": "verb", "en": "download", "hy": ["ներբեռնել"] },
  { "id": 199, "type": "verb", "en": "install", "hy": ["տեղադրել"] },
  { "id": 200, "type": "verb", "en": "uninstall", "hy": ["հեռացնել"] },
  { "id": 201, "type": "verb", "en": "execute", "hy": ["կատարել"] },
  { "id": 202, "type": "verb", "en": "perform", "hy": ["կատարել"] },
  { "id": 203, "type": "verb", "en": "operate", "hy": ["գործարկել"] },
  { "id": 204, "type": "verb", "en": "run", "hy": ["գործարկել"] },
  { "id": 205, "type": "verb", "en": "launch", "hy": ["գործարկել"] },
  { "id": 206, "type": "verb", "en": "initiate", "hy": ["սկսել"] },
  { "id": 207, "type": "verb", "en": "trigger", "hy": ["գործարկել"] },
  { "id": 208, "type": "verb", "en": "activate", "hy": ["ակտիվացնել"] },
  { "id": 209, "type": "verb", "en": "deactivate", "hy": ["ապաակտիվացնել"] },
  { "id": 210, "type": "verb", "en": "enable", "hy": ["միացնել"] },

  { "id": 211, "type": "verb", "en": "disable", "hy": ["անջատել"] },
  { "id": 212, "type": "verb", "en": "configure", "hy": ["կարգավորել"] },
  { "id": 213, "type": "verb", "en": "set", "hy": ["սահմանել"] },
  { "id": 214, "type": "verb", "en": "reset", "hy": ["վերականգնել"] },
  { "id": 215, "type": "verb", "en": "restart", "hy": ["վերագործարկել"] },
  { "id": 216, "type": "verb", "en": "reload", "hy": ["վերբեռնել"] },
  { "id": 217, "type": "verb", "en": "refresh", "hy": ["թարմացնել"] },
  { "id": 218, "type": "verb", "en": "sync", "hy": ["համաժամեցնել"] },
  { "id": 219, "type": "verb", "en": "integrate", "hy": ["ինտեգրել"] },
  { "id": 220, "type": "verb", "en": "merge", "hy": ["միավորել"] },

  { "id": 221, "type": "verb", "en": "split", "hy": ["բաժանել"] },
  { "id": 222, "type": "verb", "en": "transfer", "hy": ["փոխանցել"] },
  { "id": 223, "type": "verb", "en": "move", "hy": ["տեղափոխել"] },
  { "id": 224, "type": "verb", "en": "copy", "hy": ["պատճենել"] },
  { "id": 225, "type": "verb", "en": "paste", "hy": ["տեղադրել"] },
  { "id": 226, "type": "verb", "en": "store", "hy": ["պահել"] },
  { "id": 227, "type": "verb", "en": "save", "hy": ["պահպանել"] },
  { "id": 228, "type": "verb", "en": "backup", "hy": ["պահուստավորել"] },
  { "id": 229, "type": "verb", "en": "restore", "hy": ["վերականգնել"] },
  { "id": 230, "type": "verb", "en": "archive", "hy": ["արխիվացնել"] },

  { "id": 231, "type": "verb", "en": "delete", "hy": ["ջնջել"] },
  { "id": 232, "type": "verb", "en": "remove", "hy": ["հեռացնել"] },
  { "id": 233, "type": "verb", "en": "clear", "hy": ["մաքրել"] },
  { "id": 234, "type": "verb", "en": "clean up", "hy": ["մաքրել"] },
  { "id": 235, "type": "verb", "en": "free up", "hy": ["ազատել"] },
  { "id": 236, "type": "verb", "en": "load", "hy": ["բեռնել"] },
  { "id": 237, "type": "verb", "en": "unload", "hy": ["բեռնաթափել"] },
  { "id": 238, "type": "verb", "en": "process", "hy": ["մշակել"] },
  { "id": 239, "type": "verb", "en": "handle data", "hy": ["մշակել տվյալներ"] },
  { "id": 240, "type": "verb", "en": "filter", "hy": ["ֆիլտրել"] },

  { "id": 241, "type": "verb", "en": "sort", "hy": ["դասավորել"] },
  { "id": 242, "type": "verb", "en": "group", "hy": ["խմբավորել"] },
  { "id": 243, "type": "verb", "en": "categorize", "hy": ["կատեգորիզացնել"] },
  { "id": 244, "type": "verb", "en": "index", "hy": ["ինդեքսավորել"] },
  { "id": 245, "type": "verb", "en": "search", "hy": ["փնտրել"] },
  { "id": 246, "type": "verb", "en": "locate", "hy": ["գտնել"] },
  { "id": 247, "type": "verb", "en": "access", "hy": ["մուտք ունենալ"] },
  { "id": 248, "type": "verb", "en": "retrieve", "hy": ["վերցնել"] },
  { "id": 249, "type": "verb", "en": "fetch", "hy": ["բերել"] },
  { "id": 250, "type": "verb", "en": "pull", "hy": ["քաշել"] },

  { "id": 251, "type": "verb", "en": "push", "hy": ["հրել"] },
  { "id": 252, "type": "verb", "en": "submit", "hy": ["ուղարկել"] },
  { "id": 253, "type": "verb", "en": "apply", "hy": ["կիրառել"] },
  { "id": 254, "type": "verb", "en": "implement", "hy": ["իրականացնել"] },
  { "id": 255, "type": "verb", "en": "deploy", "hy": ["տեղադրել"] },
  { "id": 256, "type": "verb", "en": "release", "hy": ["թողարկել"] },
  { "id": 257, "type": "verb", "en": "publish", "hy": ["հրապարակել"] },
  { "id": 258, "type": "verb", "en": "distribute", "hy": ["բաշխել"] },
  { "id": 259, "type": "verb", "en": "share", "hy": ["կիսվել"] },
  { "id": 260, "type": "verb", "en": "send out", "hy": ["ուղարկել"] },

  { "id": 261, "type": "verb", "en": "receive back", "hy": ["վերադարձ ստանալ"] },
  { "id": 262, "type": "verb", "en": "process request", "hy": ["մշակել հարցում"] },
  { "id": 263, "type": "verb", "en": "handle request", "hy": ["մշակել հարցում"] },
  { "id": 264, "type": "verb", "en": "reject request", "hy": ["մերժել հարցում"] },
  { "id": 265, "type": "verb", "en": "approve request", "hy": ["հաստատել հարցում"] },
  { "id": 266, "type": "verb", "en": "accept request", "hy": ["ընդունել հարցում"] },
  { "id": 267, "type": "verb", "en": "close issue", "hy": ["փակել խնդիր"] },
  { "id": 268, "type": "verb", "en": "open issue", "hy": ["բացել խնդիր"] },
  { "id": 269, "type": "verb", "en": "resolve issue", "hy": ["լուծել խնդիր"] },
  { "id": 270, "type": "verb", "en": "escalate issue", "hy": ["բարձրացնել խնդիր"] },

  { "id": 271, "type": "verb", "en": "track issue", "hy": ["հետևել խնդրին"] },
  { "id": 272, "type": "verb", "en": "report issue", "hy": ["զեկուցել խնդիր"] },
  { "id": 273, "type": "verb", "en": "investigate", "hy": ["քննարկել"] },
  { "id": 274, "type": "verb", "en": "debug", "hy": ["վրիպակ գտնել"] },
  { "id": 275, "type": "verb", "en": "troubleshoot", "hy": ["խնդիր լուծել"] },
  { "id": 276, "type": "verb", "en": "analyze logs", "hy": ["վերլուծել լոգեր"] },
  { "id": 277, "type": "verb", "en": "check logs", "hy": ["ստուգել լոգեր"] },
  { "id": 278, "type": "verb", "en": "review logs", "hy": ["վերանայել լոգեր"] },
  { "id": 279, "type": "verb", "en": "monitor system", "hy": ["վերահսկել համակարգ"] },
  { "id": 280, "type": "verb", "en": "check status", "hy": ["ստուգել կարգավիճակ"] },

  { "id": 281, "type": "verb", "en": "update status", "hy": ["թարմացնել կարգավիճակ"] },
  { "id": 282, "type": "verb", "en": "change status", "hy": ["փոխել կարգավիճակ"] },
  { "id": 283, "type": "verb", "en": "set status", "hy": ["սահմանել կարգավիճակ"] },
  { "id": 284, "type": "verb", "en": "mark as done", "hy": ["նշել որպես ավարտված"] },
  { "id": 285, "type": "verb", "en": "mark as failed", "hy": ["նշել որպես ձախողված"] },
  { "id": 286, "type": "verb", "en": "mark as pending", "hy": ["նշել որպես սպասման մեջ"] },
  { "id": 287, "type": "verb", "en": "assign", "hy": ["նշանակել"] },
  { "id": 288, "type": "verb", "en": "reassign", "hy": ["վերանշանակել"] },
  { "id": 289, "type": "verb", "en": "take task", "hy": ["վերցնել առաջադրանք"] },
  { "id": 290, "type": "verb", "en": "complete task", "hy": ["ավարտել առաջադրանք"] },

  { "id": 291, "type": "verb", "en": "work remotely", "hy": ["աշխատել հեռակա"] },
  { "id": 292, "type": "verb", "en": "join meeting", "hy": ["մասնակցել հանդիպման"] },
  { "id": 293, "type": "verb", "en": "leave meeting", "hy": ["լքել հանդիպում"] },
  { "id": 294, "type": "verb", "en": "schedule meeting", "hy": ["պլանավորել հանդիպում"] },
  { "id": 295, "type": "verb", "en": "cancel meeting", "hy": ["չեղարկել հանդիպում"] },
  { "id": 296, "type": "verb", "en": "record meeting", "hy": ["գրանցել հանդիպում"] },
  { "id": 297, "type": "verb", "en": "share screen", "hy": ["կիսվել էկրանով"] },
  { "id": 298, "type": "verb", "en": "turn on camera", "hy": ["միացնել տեսախցիկ"] },
  { "id": 299, "type": "verb", "en": "mute microphone", "hy": ["անջատել միկրոֆոն"] },
  { "id": 300, "type": "verb", "en": "unmute", "hy": ["միացնել ձայն"] },
  { "id": 301, "type": "verb", "en": "approve request", "hy": ["հաստատել հարցում"] },
  { "id": 302, "type": "verb", "en": "reject request", "hy": ["մերժել հարցում"] },
  { "id": 303, "type": "verb", "en": "accept terms", "hy": ["ընդունել պայմանները"] },
  { "id": 304, "type": "verb", "en": "decline offer", "hy": ["մերժել առաջարկը"] },
  { "id": 305, "type": "verb", "en": "sign contract", "hy": ["ստորագրել պայմանագիր"] },
  { "id": 306, "type": "verb", "en": "break contract", "hy": ["խախտել պայմանագիր"] },
  { "id": 307, "type": "verb", "en": "extend deadline", "hy": ["երկարացնել ժամկետ"] },
  { "id": 308, "type": "verb", "en": "meet deadline", "hy": ["պահպանել ժամկետ"] },
  { "id": 309, "type": "verb", "en": "miss deadline", "hy": ["չհասնել ժամկետին"] },
  { "id": 310, "type": "verb", "en": "set deadline", "hy": ["սահմանել ժամկետ"] },

  { "id": 311, "type": "verb", "en": "prioritize task", "hy": ["առաջնահերթել առաջադրանք"] },
  { "id": 312, "type": "verb", "en": "delay task", "hy": ["ուշացնել առաջադրանք"] },
  { "id": 313, "type": "verb", "en": "assign task", "hy": ["նշանակել առաջադրանք"] },
  { "id": 314, "type": "verb", "en": "complete assignment", "hy": ["ավարտել հանձնարարություն"] },
  { "id": 315, "type": "verb", "en": "start working", "hy": ["սկսել աշխատել"] },
  { "id": 316, "type": "verb", "en": "finish work", "hy": ["ավարտել աշխատանքը"] },
  { "id": 317, "type": "verb", "en": "continue working", "hy": ["շարունակել աշխատել"] },
  { "id": 318, "type": "verb", "en": "pause work", "hy": ["դադարեցնել աշխատանքը"] },
  { "id": 319, "type": "verb", "en": "resume work", "hy": ["վերսկսել աշխատանքը"] },
  { "id": 320, "type": "verb", "en": "focus attention", "hy": ["կենտրոնացնել ուշադրությունը"] },

  { "id": 321, "type": "verb", "en": "lose focus", "hy": ["կորցնել ուշադրությունը"] },
  { "id": 322, "type": "verb", "en": "pay attention", "hy": ["ուշադրություն դարձնել"] },
  { "id": 323, "type": "verb", "en": "take responsibility", "hy": ["վերցնել պատասխանատվություն"] },
  { "id": 324, "type": "verb", "en": "avoid responsibility", "hy": ["խուսափել պատասխանատվությունից"] },
  { "id": 325, "type": "verb", "en": "solve problem", "hy": ["լուծել խնդիր"] },
  { "id": 326, "type": "verb", "en": "face problem", "hy": ["բախվել խնդրի"] },
  { "id": 327, "type": "verb", "en": "identify problem", "hy": ["հայտնաբերել խնդիր"] },
  { "id": 328, "type": "verb", "en": "report problem", "hy": ["զեկուցել խնդիր"] },
  { "id": 329, "type": "verb", "en": "fix issue", "hy": ["ուղղել խնդիր"] },
  { "id": 330, "type": "verb", "en": "escalate problem", "hy": ["բարձրացնել խնդիր"] },

  { "id": 331, "type": "verb", "en": "provide feedback", "hy": ["տրամադրել արձագանք"] },
  { "id": 332, "type": "verb", "en": "receive feedback", "hy": ["ստանալ արձագանք"] },
  { "id": 333, "type": "verb", "en": "give feedback", "hy": ["տալ արձագանք"] },
  { "id": 334, "type": "verb", "en": "request feedback", "hy": ["խնդրել արձագանք"] },
  { "id": 335, "type": "verb", "en": "improve quality", "hy": ["բարելավել որակը"] },
  { "id": 336, "type": "verb", "en": "reduce errors", "hy": ["նվազեցնել սխալները"] },
  { "id": 337, "type": "verb", "en": "increase speed", "hy": ["ավելացնել արագությունը"] },
  { "id": 338, "type": "verb", "en": "optimize process", "hy": ["օպտիմիզացնել գործընթացը"] },
  { "id": 339, "type": "verb", "en": "improve performance", "hy": ["բարելավել կատարողականությունը"] },
  { "id": 340, "type": "verb", "en": "monitor performance", "hy": ["վերահսկել կատարողականությունը"] },

  { "id": 341, "type": "verb", "en": "analyze data", "hy": ["վերլուծել տվյալները"] },
  { "id": 342, "type": "verb", "en": "collect data", "hy": ["հավաքել տվյալներ"] },
  { "id": 343, "type": "verb", "en": "process data", "hy": ["մշակել տվյալներ"] },
  { "id": 344, "type": "verb", "en": "store data", "hy": ["պահել տվյալներ"] },
  { "id": 345, "type": "verb", "en": "delete data", "hy": ["ջնջել տվյալներ"] },
  { "id": 346, "type": "verb", "en": "protect data", "hy": ["պաշտպանել տվյալներ"] },
  { "id": 347, "type": "verb", "en": "secure account", "hy": ["ապահովել հաշիվ"] },
  { "id": 348, "type": "verb", "en": "verify identity", "hy": ["հաստատել ինքնությունը"] },
  { "id": 349, "type": "verb", "en": "reset password", "hy": ["վերականգնել գաղտնաբառ"] },
  { "id": 350, "type": "verb", "en": "change password", "hy": ["փոխել գաղտնաբառ"] },

  { "id": 351, "type": "verb", "en": "log activity", "hy": ["գրանցել գործունեություն"] },
  { "id": 352, "type": "verb", "en": "track progress", "hy": ["հետևել առաջընթացին"] },
  { "id": 353, "type": "verb", "en": "measure results", "hy": ["չափել արդյունքները"] },
  { "id": 354, "type": "verb", "en": "evaluate results", "hy": ["գնահատել արդյունքները"] },
  { "id": 355, "type": "verb", "en": "compare results", "hy": ["համեմատել արդյունքները"] },
  { "id": 356, "type": "verb", "en": "improve results", "hy": ["բարելավել արդյունքները"] },
  { "id": 357, "type": "verb", "en": "deliver results", "hy": ["ներկայացնել արդյունքները"] },
  { "id": 358, "type": "verb", "en": "share results", "hy": ["կիսվել արդյունքներով"] },
  { "id": 359, "type": "verb", "en": "present results", "hy": ["ներկայացնել արդյունքները"] },
  { "id": 360, "type": "verb", "en": "review results", "hy": ["վերանայել արդյունքները"] },

  { "id": 361, "type": "verb", "en": "join team", "hy": ["միանալ թիմին"] },
  { "id": 362, "type": "verb", "en": "leave team", "hy": ["լքել թիմը"] },
  { "id": 363, "type": "verb", "en": "support team", "hy": ["աջակցել թիմին"] },
  { "id": 364, "type": "verb", "en": "lead team", "hy": ["ղեկավարել թիմը"] },
  { "id": 365, "type": "verb", "en": "manage team", "hy": ["կառավարել թիմը"] },
  { "id": 366, "type": "verb", "en": "motivate team", "hy": ["մոտիվացնել թիմը"] },
  { "id": 367, "type": "verb", "en": "train team", "hy": ["վարժեցնել թիմը"] },
  { "id": 368, "type": "verb", "en": "guide team", "hy": ["ուղղորդել թիմը"] },
  { "id": 369, "type": "verb", "en": "coordinate team", "hy": ["համակարգել թիմը"] },
  { "id": 370, "type": "verb", "en": "collaborate with team", "hy": ["համագործակցել թիմի հետ"] },

  { "id": 371, "type": "verb", "en": "communicate clearly", "hy": ["հստակ հաղորդակցվել"] },
  { "id": 372, "type": "verb", "en": "speak politely", "hy": ["քաղաքավարի խոսել"] },
  { "id": 373, "type": "verb", "en": "listen carefully", "hy": ["ուշադիր լսել"] },
  { "id": 374, "type": "verb", "en": "ask questions", "hy": ["հարցեր տալ"] },
  { "id": 375, "type": "verb", "en": "answer clearly", "hy": ["հստակ պատասխանել"] },
  { "id": 376, "type": "verb", "en": "explain simply", "hy": ["պարզ բացատրել"] },
  { "id": 377, "type": "verb", "en": "clarify details", "hy": ["պարզաբանել մանրամասները"] },
  { "id": 378, "type": "verb", "en": "give example", "hy": ["տալ օրինակ"] },
  { "id": 379, "type": "verb", "en": "describe situation", "hy": ["նկարագրել իրավիճակը"] },
  { "id": 380, "type": "verb", "en": "report status", "hy": ["զեկուցել կարգավիճակը"] },

  { "id": 381, "type": "verb", "en": "update client", "hy": ["թարմացնել հաճախորդին"] },
  { "id": 382, "type": "verb", "en": "inform manager", "hy": ["տեղեկացնել մենեջերին"] },
  { "id": 383, "type": "verb", "en": "notify team", "hy": ["տեղեկացնել թիմին"] },
  { "id": 384, "type": "verb", "en": "follow instructions", "hy": ["հետևել հրահանգներին"] },
  { "id": 385, "type": "verb", "en": "ignore issue", "hy": ["անտեսել խնդիր"] },
  { "id": 386, "type": "verb", "en": "address issue", "hy": ["զբաղվել խնդրով"] },
  { "id": 387, "type": "verb", "en": "handle situation", "hy": ["կառավարել իրավիճակը"] },
  { "id": 388, "type": "verb", "en": "solve situation", "hy": ["լուծել իրավիճակը"] },
  { "id": 389, "type": "verb", "en": "improve situation", "hy": ["բարելավել իրավիճակը"] },
  { "id": 390, "type": "verb", "en": "manage situation", "hy": ["կառավարել իրավիճակը"] },

  { "id": 391, "type": "verb", "en": "handle pressure", "hy": ["հաղթահարել ճնշումը"] },
  { "id": 392, "type": "verb", "en": "deal with stress", "hy": ["հաղթահարել սթրեսը"] },
  { "id": 393, "type": "verb", "en": "stay calm", "hy": ["մնալ հանգիստ"] },
  { "id": 394, "type": "verb", "en": "keep working", "hy": ["շարունակել աշխատել"] },
  { "id": 395, "type": "verb", "en": "work efficiently", "hy": ["աշխատել արդյունավետ"] },
  { "id": 396, "type": "verb", "en": "work quickly", "hy": ["աշխատել արագ"] },
  { "id": 397, "type": "verb", "en": "work carefully", "hy": ["աշխատել ուշադիր"] },
  { "id": 398, "type": "verb", "en": "make decision", "hy": ["կայացնել որոշում"] },
  { "id": 399, "type": "verb", "en": "take action", "hy": ["ձեռնարկել գործողություն"] },
  { "id": 400, "type": "verb", "en": "achieve goal", "hy": ["հասնել նպատակին"] },
  { "id": 401, "type": "verb", "en": "build trust", "hy": ["կառուցել վստահություն"] },
  { "id": 402, "type": "verb", "en": "gain trust", "hy": ["ձեռք բերել վստահություն"] },
  { "id": 403, "type": "verb", "en": "lose trust", "hy": ["կորցնել վստահություն"] },
  { "id": 404, "type": "verb", "en": "earn respect", "hy": ["վաստակել հարգանք"] },
  { "id": 405, "type": "verb", "en": "show respect", "hy": ["ցույց տալ հարգանք"] },
  { "id": 406, "type": "verb", "en": "take responsibility", "hy": ["վերցնել պատասխանատվություն"] },
  { "id": 407, "type": "verb", "en": "avoid mistake", "hy": ["խուսափել սխալից"] },
  { "id": 408, "type": "verb", "en": "make mistake", "hy": ["անել սխալ"] },
  { "id": 409, "type": "verb", "en": "learn from mistake", "hy": ["սովորել սխալից"] },
  { "id": 410, "type": "verb", "en": "correct mistake", "hy": ["ուղղել սխալ"] },

  { "id": 411, "type": "verb", "en": "improve skills", "hy": ["բարելավել հմտությունները"] },
  { "id": 412, "type": "verb", "en": "develop skills", "hy": ["զարգացնել հմտությունները"] },
  { "id": 413, "type": "verb", "en": "gain experience", "hy": ["ձեռք բերել փորձ"] },
  { "id": 414, "type": "verb", "en": "share experience", "hy": ["կիսվել փորձով"] },
  { "id": 415, "type": "verb", "en": "use experience", "hy": ["օգտագործել փորձը"] },
  { "id": 416, "type": "verb", "en": "apply knowledge", "hy": ["կիրառել գիտելիքը"] },
  { "id": 417, "type": "verb", "en": "gain knowledge", "hy": ["ստանալ գիտելիք"] },
  { "id": 418, "type": "verb", "en": "share knowledge", "hy": ["կիսվել գիտելիքով"] },
  { "id": 419, "type": "verb", "en": "improve knowledge", "hy": ["բարելավել գիտելիքը"] },
  { "id": 420, "type": "verb", "en": "expand knowledge", "hy": ["ընդլայնել գիտելիքը"] },

  { "id": 421, "type": "verb", "en": "understand clearly", "hy": ["հստակ հասկանալ"] },
  { "id": 422, "type": "verb", "en": "misunderstand", "hy": ["սխալ հասկանալ"] },
  { "id": 423, "type": "verb", "en": "clarify meaning", "hy": ["պարզաբանել իմաստը"] },
  { "id": 424, "type": "verb", "en": "explain again", "hy": ["նորից բացատրել"] },
  { "id": 425, "type": "verb", "en": "repeat information", "hy": ["կրկնել տեղեկությունը"] },
  { "id": 426, "type": "verb", "en": "provide details", "hy": ["տրամադրել մանրամասներ"] },
  { "id": 427, "type": "verb", "en": "ask for details", "hy": ["խնդրել մանրամասներ"] },
  { "id": 428, "type": "verb", "en": "give instructions", "hy": ["տալ հրահանգներ"] },
  { "id": 429, "type": "verb", "en": "follow instructions", "hy": ["հետևել հրահանգներին"] },
  { "id": 430, "type": "verb", "en": "ignore instructions", "hy": ["անտեսել հրահանգները"] },

  { "id": 431, "type": "verb", "en": "communicate effectively", "hy": ["արդյունավետ հաղորդակցվել"] },
  { "id": 432, "type": "verb", "en": "express opinion", "hy": ["արտահայտել կարծիք"] },
  { "id": 433, "type": "verb", "en": "share opinion", "hy": ["կիսվել կարծիքով"] },
  { "id": 434, "type": "verb", "en": "support idea", "hy": ["աջակցել գաղափարին"] },
  { "id": 435, "type": "verb", "en": "reject idea", "hy": ["մերժել գաղափարը"] },
  { "id": 436, "type": "verb", "en": "develop idea", "hy": ["զարգացնել գաղափարը"] },
  { "id": 437, "type": "verb", "en": "suggest idea", "hy": ["առաջարկել գաղափար"] },
  { "id": 438, "type": "verb", "en": "discuss idea", "hy": ["քննարկել գաղափարը"] },
  { "id": 439, "type": "verb", "en": "implement idea", "hy": ["իրականացնել գաղափարը"] },
  { "id": 440, "type": "verb", "en": "test idea", "hy": ["փորձարկել գաղափարը"] },

  { "id": 441, "type": "verb", "en": "work under pressure", "hy": ["աշխատել ճնշման տակ"] },
  { "id": 442, "type": "verb", "en": "manage stress", "hy": ["կառավարել սթրեսը"] },
  { "id": 443, "type": "verb", "en": "stay focused", "hy": ["մնալ կենտրոնացած"] },
  { "id": 444, "type": "verb", "en": "keep calm", "hy": ["մնալ հանգիստ"] },
  { "id": 445, "type": "verb", "en": "handle workload", "hy": ["կառավարել աշխատանքային բեռը"] },
  { "id": 446, "type": "verb", "en": "manage time", "hy": ["կառավարել ժամանակը"] },
  { "id": 447, "type": "verb", "en": "save time", "hy": ["խնայել ժամանակ"] },
  { "id": 448, "type": "verb", "en": "waste time", "hy": ["վատնել ժամանակ"] },
  { "id": 449, "type": "verb", "en": "spend time", "hy": ["անցկացնել ժամանակ"] },
  { "id": 450, "type": "verb", "en": "take time", "hy": ["ժամանակ պահանջել"] },

  { "id": 451, "type": "verb", "en": "build relationship", "hy": ["կառուցել հարաբերություն"] },
  { "id": 452, "type": "verb", "en": "maintain relationship", "hy": ["պահպանել հարաբերություն"] },
  { "id": 453, "type": "verb", "en": "improve relationship", "hy": ["բարելավել հարաբերություն"] },
  { "id": 454, "type": "verb", "en": "damage relationship", "hy": ["վնասել հարաբերություն"] },
  { "id": 455, "type": "verb", "en": "lose contact", "hy": ["կորցնել կապը"] },
  { "id": 456, "type": "verb", "en": "keep contact", "hy": ["պահել կապը"] },
  { "id": 457, "type": "verb", "en": "establish contact", "hy": ["հաստատել կապ"] },
  { "id": 458, "type": "verb", "en": "break contact", "hy": ["խզել կապը"] },
  { "id": 459, "type": "verb", "en": "strengthen connection", "hy": ["ուժեղացնել կապը"] },
  { "id": 460, "type": "verb", "en": "build network", "hy": ["կառուցել ցանց"] },

  { "id": 461, "type": "verb", "en": "improve communication", "hy": ["բարելավել հաղորդակցությունը"] },
  { "id": 462, "type": "verb", "en": "simplify communication", "hy": ["պարզեցնել հաղորդակցությունը"] },
  { "id": 463, "type": "verb", "en": "clarify communication", "hy": ["պարզաբանել հաղորդակցությունը"] },
  { "id": 464, "type": "verb", "en": "delay response", "hy": ["ուշացնել պատասխանը"] },
  { "id": 465, "type": "verb", "en": "speed up process", "hy": ["արագացնել գործընթացը"] },
  { "id": 466, "type": "verb", "en": "slow down process", "hy": ["դանդաղեցնել գործընթացը"] },
  { "id": 467, "type": "verb", "en": "improve process", "hy": ["բարելավել գործընթացը"] },
  { "id": 468, "type": "verb", "en": "simplify process", "hy": ["պարզեցնել գործընթացը"] },
  { "id": 469, "type": "verb", "en": "review process", "hy": ["վերանայել գործընթացը"] },
  { "id": 470, "type": "verb", "en": "change process", "hy": ["փոխել գործընթացը"] },

  { "id": 471, "type": "verb", "en": "reach agreement", "hy": ["հասնել համաձայնության"] },
  { "id": 472, "type": "verb", "en": "break agreement", "hy": ["խախտել համաձայնությունը"] },
  { "id": 473, "type": "verb", "en": "negotiate terms", "hy": ["բանակցել պայմանները"] },
  { "id": 474, "type": "verb", "en": "accept conditions", "hy": ["ընդունել պայմանները"] },
  { "id": 475, "type": "verb", "en": "reject conditions", "hy": ["մերժել պայմանները"] },
  { "id": 476, "type": "verb", "en": "review contract", "hy": ["վերանայել պայմանագիրը"] },
  { "id": 477, "type": "verb", "en": "sign agreement", "hy": ["ստորագրել համաձայնագիր"] },
  { "id": 478, "type": "verb", "en": "cancel agreement", "hy": ["չեղարկել համաձայնագիրը"] },
  { "id": 479, "type": "verb", "en": "update agreement", "hy": ["թարմացնել համաձայնագիրը"] },
  { "id": 480, "type": "verb", "en": "extend agreement", "hy": ["երկարացնել համաձայնագիրը"] },

  { "id": 481, "type": "verb", "en": "achieve success", "hy": ["հասնել հաջողության"] },
  { "id": 482, "type": "verb", "en": "face failure", "hy": ["բախվել ձախողման"] },
  { "id": 483, "type": "verb", "en": "recover from failure", "hy": ["վերականգնվել ձախողումից"] },
  { "id": 484, "type": "verb", "en": "learn quickly", "hy": ["արագ սովորել"] },
  { "id": 485, "type": "verb", "en": "adapt quickly", "hy": ["արագ հարմարվել"] },
  { "id": 486, "type": "verb", "en": "react quickly", "hy": ["արագ արձագանքել"] },
  { "id": 487, "type": "verb", "en": "respond effectively", "hy": ["արդյունավետ պատասխանել"] },
  { "id": 488, "type": "verb", "en": "work effectively", "hy": ["արդյունավետ աշխատել"] },
  { "id": 489, "type": "verb", "en": "communicate efficiently", "hy": ["արդյունավետ հաղորդակցվել"] },
  { "id": 490, "type": "verb", "en": "manage effectively", "hy": ["արդյունավետ կառավարել"] },

  { "id": 491, "type": "verb", "en": "reach solution", "hy": ["հասնել լուծման"] },
  { "id": 492, "type": "verb", "en": "find solution", "hy": ["գտնել լուծում"] },
  { "id": 493, "type": "verb", "en": "create solution", "hy": ["ստեղծել լուծում"] },
  { "id": 494, "type": "verb", "en": "test solution", "hy": ["փորձարկել լուծումը"] },
  { "id": 495, "type": "verb", "en": "improve solution", "hy": ["բարելավել լուծումը"] },
  { "id": 496, "type": "verb", "en": "apply solution", "hy": ["կիրառել լուծումը"] },
  { "id": 497, "type": "verb", "en": "evaluate solution", "hy": ["գնահատել լուծումը"] },
  { "id": 498, "type": "verb", "en": "review solution", "hy": ["վերանայել լուծումը"] },
  { "id": 499, "type": "verb", "en": "accept solution", "hy": ["ընդունել լուծումը"] },
  { "id": 500, "type": "verb", "en": "reject solution", "hy": ["մերժել լուծումը"] },
  { "id": 501, "type": "communication", "en": "agreement", "hy": ["համաձայնություն"] },
  { "id": 502, "type": "communication", "en": "discussion", "hy": ["քննարկում"] },
  { "id": 503, "type": "communication", "en": "decision", "hy": ["որոշում"] },
  { "id": 504, "type": "communication", "en": "suggestion", "hy": ["առաջարկ"] },
  { "id": 505, "type": "communication", "en": "opinion", "hy": ["կարծիք"] },
  { "id": 506, "type": "communication", "en": "feedback", "hy": ["արձագանք"] },
  { "id": 507, "type": "communication", "en": "comment", "hy": ["մեկնաբանություն"] },
  { "id": 508, "type": "communication", "en": "question", "hy": ["հարց"] },
  { "id": 509, "type": "communication", "en": "answer", "hy": ["պատասխան"] },
  { "id": 510, "type": "communication", "en": "response", "hy": ["պատասխան", "արձագանք"] },

  { "id": 511, "type": "communication", "en": "request", "hy": ["հարցում", "խնդրանք"] },
  { "id": 512, "type": "communication", "en": "requirement", "hy": ["պահանջ"] },
  { "id": 513, "type": "communication", "en": "expectation", "hy": ["ակնկալիք"] },
  { "id": 514, "type": "communication", "en": "responsibility", "hy": ["պատասխանատվություն"] },
  { "id": 515, "type": "communication", "en": "priority", "hy": ["առաջնահերթություն"] },
  { "id": 516, "type": "communication", "en": "deadline", "hy": ["ժամկետ"] },
  { "id": 517, "type": "communication", "en": "task", "hy": ["առաջադրանք"] },
  { "id": 518, "type": "communication", "en": "assignment", "hy": ["հանձնարարություն"] },
  { "id": 519, "type": "communication", "en": "project", "hy": ["նախագիծ"] },
  { "id": 520, "type": "communication", "en": "goal", "hy": ["նպատակ"] },

  { "id": 521, "type": "communication", "en": "target", "hy": ["թիրախ", "նպատակ"] },
  { "id": 522, "type": "communication", "en": "plan", "hy": ["պլան", "ծրագիր"] },
  { "id": 523, "type": "communication", "en": "strategy", "hy": ["ռազմավարություն"] },
  { "id": 524, "type": "communication", "en": "approach", "hy": ["մոտեցում"] },
  { "id": 525, "type": "communication", "en": "method", "hy": ["մեթոդ"] },
  { "id": 526, "type": "communication", "en": "process", "hy": ["գործընթաց"] },
  { "id": 527, "type": "communication", "en": "step", "hy": ["քայլ"] },
  { "id": 528, "type": "communication", "en": "stage", "hy": ["փուլ"] },
  { "id": 529, "type": "communication", "en": "progress", "hy": ["առաջընթաց"] },
  { "id": 530, "type": "communication", "en": "result", "hy": ["արդյունք"] },

  { "id": 531, "type": "communication", "en": "outcome", "hy": ["արդյունք"] },
  { "id": 532, "type": "communication", "en": "success", "hy": ["հաջողություն"] },
  { "id": 533, "type": "communication", "en": "failure", "hy": ["ձախողում"] },
  { "id": 534, "type": "communication", "en": "risk", "hy": ["ռիսկ"] },
  { "id": 535, "type": "communication", "en": "issue", "hy": ["խնդիր"] },
  { "id": 536, "type": "communication", "en": "problem", "hy": ["խնդիր"] },
  { "id": 537, "type": "communication", "en": "solution", "hy": ["լուծում"] },
  { "id": 538, "type": "communication", "en": "reason", "hy": ["պատճառ"] },
  { "id": 539, "type": "communication", "en": "cause", "hy": ["պատճառ"] },
  { "id": 540, "type": "communication", "en": "effect", "hy": ["ազդեցություն"] },

  { "id": 541, "type": "communication", "en": "impact", "hy": ["ազդեցություն"] },
  { "id": 542, "type": "communication", "en": "benefit", "hy": ["օգուտ", "առավելություն"] },
  { "id": 543, "type": "communication", "en": "advantage", "hy": ["առավելություն"] },
  { "id": 544, "type": "communication", "en": "disadvantage", "hy": ["թերություն"] },
  { "id": 545, "type": "communication", "en": "challenge", "hy": ["մարտահրավեր"] },
  { "id": 546, "type": "communication", "en": "difficulty", "hy": ["դժվարություն"] },
  { "id": 547, "type": "communication", "en": "opportunity", "hy": ["հնարավորություն"] },
  { "id": 548, "type": "communication", "en": "possibility", "hy": ["հնարավորություն"] },
  { "id": 549, "type": "communication", "en": "option", "hy": ["տարբերակ", "ընտրանք"] },
  { "id": 550, "type": "communication", "en": "choice", "hy": ["ընտրություն"] },

  { "id": 551, "type": "communication", "en": "alternative", "hy": ["այլընտրանք"] },
  { "id": 552, "type": "communication", "en": "condition", "hy": ["պայման"] },
  { "id": 553, "type": "communication", "en": "situation", "hy": ["իրավիճակ"] },
  { "id": 554, "type": "communication", "en": "case", "hy": ["դեպք"] },
  { "id": 555, "type": "communication", "en": "example", "hy": ["օրինակ"] },
  { "id": 556, "type": "communication", "en": "details", "hy": ["մանրամասներ"] },
  { "id": 557, "type": "communication", "en": "description", "hy": ["նկարագրություն"] },
  { "id": 558, "type": "communication", "en": "information", "hy": ["տեղեկություն"] },
  { "id": 559, "type": "communication", "en": "data", "hy": ["տվյալներ"] },
  { "id": 560, "type": "communication", "en": "source", "hy": ["աղբյուր"] },

  { "id": 561, "type": "communication", "en": "knowledge", "hy": ["գիտելիք"] },
  { "id": 562, "type": "communication", "en": "experience", "hy": ["փորձ"] },
  { "id": 563, "type": "communication", "en": "skill", "hy": ["հմտություն"] },
  { "id": 564, "type": "communication", "en": "ability", "hy": ["կարողություն"] },
  { "id": 565, "type": "communication", "en": "level", "hy": ["մակարդակ"] },
  { "id": 566, "type": "communication", "en": "quality", "hy": ["որակ"] },
  { "id": 567, "type": "communication", "en": "performance", "hy": ["կատարողականություն", "աշխատանքի արդյունք"] },
  { "id": 568, "type": "communication", "en": "improvement", "hy": ["բարելավում"] },
  { "id": 569, "type": "communication", "en": "change", "hy": ["փոփոխություն"] },
  { "id": 570, "type": "communication", "en": "update", "hy": ["թարմացում"] },

  { "id": 571, "type": "communication", "en": "status", "hy": ["կարգավիճակ"] },
  { "id": 572, "type": "communication", "en": "summary", "hy": ["ամփոփում"] },
  { "id": 573, "type": "communication", "en": "report", "hy": ["հաշվետվություն"] },
  { "id": 574, "type": "communication", "en": "note", "hy": ["նշում"] },
  { "id": 575, "type": "communication", "en": "message", "hy": ["հաղորդագրություն"] },
  { "id": 576, "type": "communication", "en": "email", "hy": ["էլ․ նամակ"] },
  { "id": 577, "type": "communication", "en": "call", "hy": ["զանգ"] },
  { "id": 578, "type": "communication", "en": "meeting", "hy": ["հանդիպում", "ժողով"] },
  { "id": 579, "type": "communication", "en": "conversation", "hy": ["զրույց"] },
  { "id": 580, "type": "communication", "en": "communication", "hy": ["հաղորդակցություն"] },

  { "id": 581, "type": "communication", "en": "clarification", "hy": ["պարզաբանում"] },
  { "id": 582, "type": "communication", "en": "confirmation", "hy": ["հաստատում"] },
  { "id": 583, "type": "communication", "en": "approval", "hy": ["հաստատում", "հավանություն"] },
  { "id": 584, "type": "communication", "en": "permission", "hy": ["թույլտվություն"] },
  { "id": 585, "type": "communication", "en": "instruction", "hy": ["հրահանգ"] },
  { "id": 586, "type": "communication", "en": "guideline", "hy": ["ուղեցույց"] },
  { "id": 587, "type": "communication", "en": "rule", "hy": ["կանոն"] },
  { "id": 588, "type": "communication", "en": "policy", "hy": ["քաղաքականություն"] },
  { "id": 589, "type": "communication", "en": "procedure", "hy": ["ընթացակարգ"] },
  { "id": 590, "type": "communication", "en": "standard", "hy": ["ստանդարտ"] },

  { "id": 591, "type": "communication", "en": "document", "hy": ["փաստաթուղթ"] },
  { "id": 592, "type": "communication", "en": "file", "hy": ["ֆայլ"] },
  { "id": 593, "type": "communication", "en": "attachment", "hy": ["կցված ֆայլ"] },
  { "id": 594, "type": "communication", "en": "link", "hy": ["հղում"] },
  { "id": 595, "type": "communication", "en": "reference", "hy": ["հղում", "տեղեկանք"] },
  { "id": 596, "type": "communication", "en": "template", "hy": ["ձևանմուշ"] },
  { "id": 597, "type": "communication", "en": "format", "hy": ["ձևաչափ"] },
  { "id": 598, "type": "communication", "en": "version", "hy": ["տարբերակ"] },
  { "id": 599, "type": "communication", "en": "draft", "hy": ["սևագիր"] },
  { "id": 600, "type": "communication", "en": "final version", "hy": ["վերջնական տարբերակ"] },
  { "id": 601, "type": "communication", "en": "let me know", "hy": ["ինձ տեղյակ պահիր"] },
  { "id": 602, "type": "communication", "en": "please confirm", "hy": ["խնդրում եմ հաստատեք"] },
  { "id": 603, "type": "communication", "en": "just to clarify", "hy": ["պարզաբանելու համար"] },
  { "id": 604, "type": "communication", "en": "as discussed", "hy": ["ինչպես քննարկվել է"] },
  { "id": 605, "type": "communication", "en": "as mentioned", "hy": ["ինչպես նշվել է"] },
  { "id": 606, "type": "communication", "en": "for your information", "hy": ["ձեր տեղեկության համար"] },
  { "id": 607, "type": "communication", "en": "please check", "hy": ["խնդրում եմ ստուգեք"] },
  { "id": 608, "type": "communication", "en": "take a look", "hy": ["նայեք"] },
  { "id": 609, "type": "communication", "en": "feel free to ask", "hy": ["ազատ զգացեք հարցնել"] },
  { "id": 610, "type": "communication", "en": "no worries", "hy": ["ոչ մի խնդիր"] },

  { "id": 611, "type": "communication", "en": "sounds good", "hy": ["լավ է հնչում"] },
  { "id": 612, "type": "communication", "en": "makes sense", "hy": ["իմաստ ունի"] },
  { "id": 613, "type": "communication", "en": "I agree", "hy": ["համաձայն եմ"] },
  { "id": 614, "type": "communication", "en": "I disagree", "hy": ["համաձայն չեմ"] },
  { "id": 615, "type": "communication", "en": "good point", "hy": ["լավ միտք"] },
  { "id": 616, "type": "communication", "en": "that works", "hy": ["դա հարմար է"] },
  { "id": 617, "type": "communication", "en": "that won't work", "hy": ["դա չի աշխատի"] },
  { "id": 618, "type": "communication", "en": "we can try", "hy": ["կարող ենք փորձել"] },
  { "id": 619, "type": "communication", "en": "let's try this", "hy": ["փորձենք սա"] },
  { "id": 620, "type": "communication", "en": "we need to check", "hy": ["պետք է ստուգենք"] },

  { "id": 621, "type": "communication", "en": "I will check", "hy": ["կստուգեմ"] },
  { "id": 622, "type": "communication", "en": "I will confirm", "hy": ["կհաստատեմ"] },
  { "id": 623, "type": "communication", "en": "I will update you", "hy": ["կթարմացնեմ ձեզ"] },
  { "id": 624, "type": "communication", "en": "I will get back to you", "hy": ["կվերադառնամ ձեզ մոտ"] },
  { "id": 625, "type": "communication", "en": "checking now", "hy": ["ստուգում եմ հիմա"] },
  { "id": 626, "type": "communication", "en": "working on it", "hy": ["աշխատում եմ դրա վրա"] },
  { "id": 627, "type": "communication", "en": "in progress", "hy": ["ընթացքի մեջ է"] },
  { "id": 628, "type": "communication", "en": "almost done", "hy": ["գրեթե պատրաստ է"] },
  { "id": 629, "type": "communication", "en": "done", "hy": ["պատրաստ է"] },
  { "id": 630, "type": "communication", "en": "completed", "hy": ["ավարտված է"] },

  { "id": 631, "type": "communication", "en": "not yet", "hy": ["ոչ դեռ"] },
  { "id": 632, "type": "communication", "en": "still pending", "hy": ["դեռ սպասման մեջ է"] },
  { "id": 633, "type": "communication", "en": "delayed", "hy": ["ուշացած"] },
  { "id": 634, "type": "communication", "en": "on hold", "hy": ["կասեցված"] },
  { "id": 635, "type": "communication", "en": "blocked", "hy": ["արգելափակված"] },
  { "id": 636, "type": "communication", "en": "issue found", "hy": ["խնդիր է հայտնաբերվել"] },
  { "id": 637, "type": "communication", "en": "please fix", "hy": ["խնդրում եմ ուղղեք"] },
  { "id": 638, "type": "communication", "en": "needs improvement", "hy": ["պետք է բարելավել"] },
  { "id": 639, "type": "communication", "en": "not correct", "hy": ["ճիշտ չէ"] },
  { "id": 640, "type": "communication", "en": "incorrect", "hy": ["սխալ"] },

  { "id": 641, "type": "communication", "en": "correct", "hy": ["ճիշտ"] },
  { "id": 642, "type": "communication", "en": "verified", "hy": ["ստուգված"] },
  { "id": 643, "type": "communication", "en": "approved", "hy": ["հաստատված"] },
  { "id": 644, "type": "communication", "en": "rejected", "hy": ["մերժված"] },
  { "id": 645, "type": "communication", "en": "review needed", "hy": ["պետք է ստուգել"] },
  { "id": 646, "type": "communication", "en": "please review", "hy": ["խնդրում եմ վերանայեք"] },
  { "id": 647, "type": "communication", "en": "double check", "hy": ["երկակի ստուգում արեք"] },
  { "id": 648, "type": "communication", "en": "take another look", "hy": ["կրկին նայեք"] },
  { "id": 649, "type": "communication", "en": "looks fine", "hy": ["նորմալ է"] },
  { "id": 650, "type": "communication", "en": "looks good to me", "hy": ["ինձ համար լավ է"] },

  { "id": 651, "type": "communication", "en": "from our side", "hy": ["մեր կողմից"] },
  { "id": 652, "type": "communication", "en": "on your side", "hy": ["ձեր կողմից"] },
  { "id": 653, "type": "communication", "en": "as per request", "hy": ["ըստ խնդրանքի"] },
  { "id": 654, "type": "communication", "en": "as agreed", "hy": ["ինչպես պայմանավորվել ենք"] },
  { "id": 655, "type": "communication", "en": "based on this", "hy": ["սրա հիման վրա"] },
  { "id": 656, "type": "communication", "en": "according to", "hy": ["համաձայն"] },
  { "id": 657, "type": "communication", "en": "in this case", "hy": ["այս դեպքում"] },
  { "id": 658, "type": "communication", "en": "in general", "hy": ["ընդհանուր առմամբ"] },
  { "id": 659, "type": "communication", "en": "for example", "hy": ["օրինակ"] },
  { "id": 660, "type": "communication", "en": "for instance", "hy": ["օրինակ"] },

  { "id": 661, "type": "communication", "en": "next step", "hy": ["հաջորդ քայլ"] },
  { "id": 662, "type": "communication", "en": "final step", "hy": ["վերջնական քայլ"] },
  { "id": 663, "type": "communication", "en": "first step", "hy": ["առաջին քայլ"] },
  { "id": 664, "type": "communication", "en": "step by step", "hy": ["քայլ առ քայլ"] },
  { "id": 665, "type": "communication", "en": "timeline", "hy": ["ժամանակացույց"] },
  { "id": 666, "type": "communication", "en": "schedule", "hy": ["ժամանակացույց"] },
  { "id": 667, "type": "communication", "en": "timeframe", "hy": ["ժամանակահատված"] },
  { "id": 668, "type": "communication", "en": "estimate", "hy": ["գնահատում"] },
  { "id": 669, "type": "communication", "en": "approximate", "hy": ["մոտավոր"] },
  { "id": 670, "type": "communication", "en": "exact", "hy": ["ճշգրիտ"] },

  { "id": 671, "type": "communication", "en": "high priority", "hy": ["բարձր առաջնահերթություն"] },
  { "id": 672, "type": "communication", "en": "low priority", "hy": ["ցածր առաջնահերթություն"] },
  { "id": 673, "type": "communication", "en": "urgent", "hy": ["շտապ"] },
  { "id": 674, "type": "communication", "en": "important", "hy": ["կարևոր"] },
  { "id": 675, "type": "communication", "en": "optional", "hy": ["ընտրովի"] },
  { "id": 676, "type": "communication", "en": "required", "hy": ["պահանջվող"] },
  { "id": 677, "type": "communication", "en": "mandatory", "hy": ["պարտադիր"] },
  { "id": 678, "type": "communication", "en": "recommended", "hy": ["խորհուրդ տրվող"] },
  { "id": 679, "type": "communication", "en": "suggested", "hy": ["առաջարկվող"] },
  { "id": 680, "type": "communication", "en": "possible", "hy": ["հնարավոր"] },

  { "id": 681, "type": "communication", "en": "not possible", "hy": ["հնարավոր չէ"] },
  { "id": 682, "type": "communication", "en": "available", "hy": ["հասանելի"] },
  { "id": 683, "type": "communication", "en": "not available", "hy": ["հասանելի չէ"] },
  { "id": 684, "type": "communication", "en": "enabled", "hy": ["ակտիվացված"] },
  { "id": 685, "type": "communication", "en": "disabled", "hy": ["անջատված"] },
  { "id": 686, "type": "communication", "en": "active", "hy": ["ակտիվ"] },
  { "id": 687, "type": "communication", "en": "inactive", "hy": ["ոչ ակտիվ"] },
  { "id": 688, "type": "communication", "en": "valid", "hy": ["վավեր"] },
  { "id": 689, "type": "communication", "en": "invalid", "hy": ["անվավեր"] },
  { "id": 690, "type": "communication", "en": "expired", "hy": ["ժամկետանց"] },

  { "id": 691, "type": "communication", "en": "working", "hy": ["աշխատում է"] },
  { "id": 692, "type": "communication", "en": "not working", "hy": ["չի աշխատում"] },
  { "id": 693, "type": "communication", "en": "fixed", "hy": ["ուղղված"] },
  { "id": 694, "type": "communication", "en": "bug", "hy": ["սխալ"] },
  { "id": 695, "type": "communication", "en": "error", "hy": ["սխալ"] },
  { "id": 696, "type": "communication", "en": "issue resolved", "hy": ["խնդիրը լուծված է"] },
  { "id": 697, "type": "communication", "en": "reproduced", "hy": ["վերարտադրված է"] },
  { "id": 698, "type": "communication", "en": "cannot reproduce", "hy": ["չի վերարտադրվում"] },
  { "id": 699, "type": "communication", "en": "need more info", "hy": ["պետք է ավելի շատ տեղեկություն"] },
  { "id": 700, "type": "communication", "en": "please provide details", "hy": ["խնդրում եմ տրամադրեք մանրամասներ"] },
  { "id": 701, "type": "communication", "en": "API request", "hy": ["API հարցում"] },
  { "id": 702, "type": "communication", "en": "API response", "hy": ["API պատասխան"] },
  { "id": 703, "type": "communication", "en": "endpoint", "hy": ["endpoint"] },
  { "id": 704, "type": "communication", "en": "payload", "hy": ["տվյալների փաթեթ"] },
  { "id": 705, "type": "communication", "en": "request body", "hy": ["հարցման մարմին"] },
  { "id": 706, "type": "communication", "en": "response body", "hy": ["պատասխանի մարմին"] },
  { "id": 707, "type": "communication", "en": "header", "hy": ["վերնագիր"] },
  { "id": 708, "type": "communication", "en": "status code", "hy": ["կարգավիճակի կոդ"] },
  { "id": 709, "type": "communication", "en": "error code", "hy": ["սխալի կոդ"] },
  { "id": 710, "type": "communication", "en": "success response", "hy": ["հաջող պատասխան"] },

  { "id": 711, "type": "communication", "en": "failed response", "hy": ["ձախողված պատասխան"] },
  { "id": 712, "type": "communication", "en": "timeout", "hy": ["ժամկետի ավարտ"] },
  { "id": 713, "type": "communication", "en": "retry", "hy": ["կրկնել"] },
  { "id": 714, "type": "communication", "en": "request failed", "hy": ["հարցումը ձախողվեց"] },
  { "id": 715, "type": "communication", "en": "connection error", "hy": ["կապի սխալ"] },
  { "id": 716, "type": "communication", "en": "server error", "hy": ["սերվերի սխալ"] },
  { "id": 717, "type": "communication", "en": "client error", "hy": ["հաճախորդի սխալ"] },
  { "id": 718, "type": "communication", "en": "invalid request", "hy": ["անվավեր հարցում"] },
  { "id": 719, "type": "communication", "en": "valid request", "hy": ["վավեր հարցում"] },
  { "id": 720, "type": "communication", "en": "missing parameter", "hy": ["պակասող պարամետր"] },

  { "id": 721, "type": "communication", "en": "invalid parameter", "hy": ["անվավեր պարամետր"] },
  { "id": 722, "type": "communication", "en": "required field", "hy": ["պարտադիր դաշտ"] },
  { "id": 723, "type": "communication", "en": "optional field", "hy": ["ընտրովի դաշտ"] },
  { "id": 724, "type": "communication", "en": "data mismatch", "hy": ["տվյալների անհամապատասխանություն"] },
  { "id": 725, "type": "communication", "en": "duplicate request", "hy": ["կրկնվող հարցում"] },
  { "id": 726, "type": "communication", "en": "unique id", "hy": ["յուրահատուկ id"] },
  { "id": 727, "type": "communication", "en": "transaction id", "hy": ["տրանզակցիայի id"] },
  { "id": 728, "type": "communication", "en": "round id", "hy": ["ռաունդի id"] },
  { "id": 729, "type": "communication", "en": "user id", "hy": ["օգտատիրոջ id"] },
  { "id": 730, "type": "communication", "en": "session id", "hy": ["սեսիայի id"] },

  { "id": 731, "type": "communication", "en": "token", "hy": ["թոքեն"] },
  { "id": 732, "type": "communication", "en": "access token", "hy": ["մուտքի թոքեն"] },
  { "id": 733, "type": "communication", "en": "expired token", "hy": ["ժամկետանց թոքեն"] },
  { "id": 734, "type": "communication", "en": "invalid token", "hy": ["անվավեր թոքեն"] },
  { "id": 735, "type": "communication", "en": "authentication", "hy": ["ավտորիզացում"] },
  { "id": 736, "type": "communication", "en": "authorization", "hy": ["թույլտվություն"] },
  { "id": 737, "type": "communication", "en": "login", "hy": ["մուտք"] },
  { "id": 738, "type": "communication", "en": "logout", "hy": ["ելք"] },
  { "id": 739, "type": "communication", "en": "credentials", "hy": ["մուտքի տվյալներ"] },
  { "id": 740, "type": "communication", "en": "secret key", "hy": ["գաղտնի բանալի"] },

  { "id": 741, "type": "communication", "en": "invalid credentials", "hy": ["անվավեր տվյալներ"] },
  { "id": 742, "type": "communication", "en": "access denied", "hy": ["մուտքը արգելված է"] },
  { "id": 743, "type": "communication", "en": "permission denied", "hy": ["թույլտվությունը մերժված է"] },
  { "id": 744, "type": "communication", "en": "rate limit", "hy": ["սահմանափակում"] },
  { "id": 745, "type": "communication", "en": "too many requests", "hy": ["շատ հարցումներ"] },
  { "id": 746, "type": "communication", "en": "request limit exceeded", "hy": ["սահմանը գերազանցված է"] },
  { "id": 747, "type": "communication", "en": "throttling", "hy": ["սահմանափակում"] },
  { "id": 748, "type": "communication", "en": "response time", "hy": ["պատասխանի ժամանակ"] },
  { "id": 749, "type": "communication", "en": "latency", "hy": ["ուշացում"] },
  { "id": 750, "type": "communication", "en": "performance issue", "hy": ["կատարողականի խնդիր"] },

  { "id": 751, "type": "communication", "en": "load test", "hy": ["բեռնվածության թեստ"] },
  { "id": 752, "type": "communication", "en": "stress test", "hy": ["սթրես թեստ"] },
  { "id": 753, "type": "communication", "en": "test case", "hy": ["թեստի դեպք"] },
  { "id": 754, "type": "communication", "en": "test result", "hy": ["թեստի արդյունք"] },
  { "id": 755, "type": "communication", "en": "test environment", "hy": ["թեստ միջավայր"] },
  { "id": 756, "type": "communication", "en": "production environment", "hy": ["արտադրական միջավայր"] },
  { "id": 757, "type": "communication", "en": "staging environment", "hy": ["թեստային միջավայր"] },
  { "id": 758, "type": "communication", "en": "deployment", "hy": ["տեղադրում"] },
  { "id": 759, "type": "communication", "en": "release", "hy": ["թողարկում"] },
  { "id": 760, "type": "communication", "en": "version update", "hy": ["տարբերակի թարմացում"] },

  { "id": 761, "type": "communication", "en": "rollback", "hy": ["հետ վերադարձ"] },
  { "id": 762, "type": "communication", "en": "integration", "hy": ["ինտեգրում"] },
  { "id": 763, "type": "communication", "en": "integration issue", "hy": ["ինտեգրման խնդիր"] },
  { "id": 764, "type": "communication", "en": "partner system", "hy": ["գործընկեր համակարգ"] },
  { "id": 765, "type": "communication", "en": "provider", "hy": ["պրովայդեր"] },
  { "id": 766, "type": "communication", "en": "operator", "hy": ["օպերատոր"] },
  { "id": 767, "type": "communication", "en": "aggregator", "hy": ["ագրեգատոր"] },
  { "id": 768, "type": "communication", "en": "callback", "hy": ["հետ կանչ"] },
  { "id": 769, "type": "communication", "en": "webhook", "hy": ["webhook"] },
  { "id": 770, "type": "communication", "en": "request log", "hy": ["հարցման լոգ"] },

  { "id": 771, "type": "communication", "en": "response log", "hy": ["պատասխանի լոգ"] },
  { "id": 772, "type": "communication", "en": "error log", "hy": ["սխալի լոգ"] },
  { "id": 773, "type": "communication", "en": "debug", "hy": ["դեբագ"] },
  { "id": 774, "type": "communication", "en": "investigation", "hy": ["քննություն"] },
  { "id": 775, "type": "communication", "en": "root cause", "hy": ["հիմնական պատճառ"] },
  { "id": 776, "type": "communication", "en": "temporary fix", "hy": ["ժամանակավոր լուծում"] },
  { "id": 777, "type": "communication", "en": "permanent fix", "hy": ["մշտական լուծում"] },
  { "id": 778, "type": "communication", "en": "workaround", "hy": ["ժամանակավոր լուծում"] },
  { "id": 779, "type": "communication", "en": "retest", "hy": ["կրկնակի թեստ"] },
  { "id": 780, "type": "communication", "en": "verified fix", "hy": ["ստուգված լուծում"] },

  { "id": 781, "type": "communication", "en": "can you check this", "hy": ["կարող եք ստուգել սա"] },
  { "id": 782, "type": "communication", "en": "please investigate", "hy": ["խնդրում եմ ուսումնասիրեք"] },
  { "id": 783, "type": "communication", "en": "we found an issue", "hy": ["մենք գտել ենք խնդիր"] },
  { "id": 784, "type": "communication", "en": "we cannot reproduce", "hy": ["չենք կարող վերարտադրել"] },
  { "id": 785, "type": "communication", "en": "can you provide logs", "hy": ["կարող եք տրամադրել լոգերը"] },
  { "id": 786, "type": "communication", "en": "please share details", "hy": ["խնդրում եմ կիսվեք մանրամասներով"] },
  { "id": 787, "type": "communication", "en": "need more information", "hy": ["պետք է ավելի շատ տեղեկություն"] },
  { "id": 788, "type": "communication", "en": "what is expected behavior", "hy": ["ինչ է սպասվող վարքագիծը"] },
  { "id": 789, "type": "communication", "en": "what is actual behavior", "hy": ["ինչ է իրական վարքագիծը"] },
  { "id": 790, "type": "communication", "en": "steps to reproduce", "hy": ["վերարտադրելու քայլեր"] },

  { "id": 791, "type": "communication", "en": "issue is fixed", "hy": ["խնդիրը ուղղված է"] },
  { "id": 792, "type": "communication", "en": "please verify", "hy": ["խնդրում եմ ստուգեք"] },
  { "id": 793, "type": "communication", "en": "closing the issue", "hy": ["փակում ենք խնդիրը"] },
  { "id": 794, "type": "communication", "en": "reopening the issue", "hy": ["վերաբացում ենք խնդիրը"] },
  { "id": 795, "type": "communication", "en": "ticket created", "hy": ["ստեղծվել է տիկետ"] },
  { "id": 796, "type": "communication", "en": "ticket updated", "hy": ["թարմացվել է տիկետը"] },
  { "id": 797, "type": "communication", "en": "ticket closed", "hy": ["տիկետը փակված է"] },
  { "id": 798, "type": "communication", "en": "assigned to", "hy": ["նշանակված է"] },
  { "id": 799, "type": "communication", "en": "waiting for response", "hy": ["սպասում ենք պատասխանի"] },
  { "id": 800, "type": "communication", "en": "awaiting feedback", "hy": ["սպասում ենք արձագանքի"] },
  { "id": 801, "type": "communication", "en": "hey team", "hy": ["բարև թիմ"] },
  { "id": 802, "type": "communication", "en": "hi everyone", "hy": ["բարև բոլորին"] },
  { "id": 803, "type": "communication", "en": "quick update", "hy": ["արագ թարմացում"] },
  { "id": 804, "type": "communication", "en": "small update", "hy": ["փոքր թարմացում"] },
  { "id": 805, "type": "communication", "en": "status update", "hy": ["կարգավիճակի թարմացում"] },
  { "id": 806, "type": "communication", "en": "sharing an update", "hy": ["կիսվում եմ թարմացմամբ"] },
  { "id": 807, "type": "communication", "en": "just an update", "hy": ["ուղղակի թարմացում"] },
  { "id": 808, "type": "communication", "en": "latest update", "hy": ["վերջին թարմացում"] },
  { "id": 809, "type": "communication", "en": "any updates", "hy": ["կա թարմացում"] },
  { "id": 810, "type": "communication", "en": "any news", "hy": ["կա նորություն"] },

  { "id": 811, "type": "communication", "en": "following up", "hy": ["հետևում եմ"] },
  { "id": 812, "type": "communication", "en": "just following up", "hy": ["ուղղակի հիշեցում"] },
  { "id": 813, "type": "communication", "en": "friendly reminder", "hy": ["ընկերական հիշեցում"] },
  { "id": 814, "type": "communication", "en": "any progress", "hy": ["կա առաջընթաց"] },
  { "id": 815, "type": "communication", "en": "any feedback", "hy": ["կա արձագանք"] },
  { "id": 816, "type": "communication", "en": "waiting for update", "hy": ["սպասում ենք թարմացման"] },
  { "id": 817, "type": "communication", "en": "still waiting", "hy": ["դեռ սպասում ենք"] },
  { "id": 818, "type": "communication", "en": "please update us", "hy": ["խնդրում ենք թարմացրեք"] },
  { "id": 819, "type": "communication", "en": "let us know once done", "hy": ["տեղյակ պահեք ավարտելուց հետո"] },
  { "id": 820, "type": "communication", "en": "keep us posted", "hy": ["տեղյակ պահեք"] },

  { "id": 821, "type": "communication", "en": "thanks for the update", "hy": ["շնորհակալություն թարմացման համար"] },
  { "id": 822, "type": "communication", "en": "thanks for checking", "hy": ["շնորհակալություն ստուգելու համար"] },
  { "id": 823, "type": "communication", "en": "thanks for confirming", "hy": ["շնորհակալություն հաստատելու համար"] },
  { "id": 824, "type": "communication", "en": "appreciate it", "hy": ["գնահատում ենք"] },
  { "id": 825, "type": "communication", "en": "much appreciated", "hy": ["շատ գնահատելի է"] },
  { "id": 826, "type": "communication", "en": "thank you in advance", "hy": ["նախապես շնորհակալություն"] },
  { "id": 827, "type": "communication", "en": "thanks in advance", "hy": ["շնորհակալություն նախապես"] },
  { "id": 828, "type": "communication", "en": "sorry for the delay", "hy": ["ներողություն ուշացման համար"] },
  { "id": 829, "type": "communication", "en": "apologies for the delay", "hy": ["ներողություն ուշացման համար"] },
  { "id": 830, "type": "communication", "en": "sorry for late reply", "hy": ["ներողություն ուշ պատասխանի համար"] },

  { "id": 831, "type": "communication", "en": "no problem", "hy": ["ոչ մի խնդիր"] },
  { "id": 832, "type": "communication", "en": "all good", "hy": ["ամեն ինչ նորմալ է"] },
  { "id": 833, "type": "communication", "en": "no issues from our side", "hy": ["մեր կողմից խնդիր չկա"] },
  { "id": 834, "type": "communication", "en": "everything works fine", "hy": ["ամեն ինչ նորմալ է աշխատում"] },
  { "id": 835, "type": "communication", "en": "looks correct", "hy": ["ճիշտ է թվում"] },
  { "id": 836, "type": "communication", "en": "works as expected", "hy": ["աշխատում է ինչպես սպասվում էր"] },
  { "id": 837, "type": "communication", "en": "not working as expected", "hy": ["չի աշխատում ինչպես սպասվում էր"] },
  { "id": 838, "type": "communication", "en": "still not working", "hy": ["դեռ չի աշխատում"] },
  { "id": 839, "type": "communication", "en": "issue still exists", "hy": ["խնդիրը դեռ կա"] },
  { "id": 840, "type": "communication", "en": "issue persists", "hy": ["խնդիրը շարունակում է լինել"] },

  { "id": 841, "type": "communication", "en": "please check again", "hy": ["խնդրում ենք կրկին ստուգեք"] },
  { "id": 842, "type": "communication", "en": "please recheck", "hy": ["խնդրում ենք վերաստուգեք"] },
  { "id": 843, "type": "communication", "en": "please fix this issue", "hy": ["խնդրում ենք ուղղեք խնդիրը"] },
  { "id": 844, "type": "communication", "en": "this needs to be fixed", "hy": ["սա պետք է ուղղվի"] },
  { "id": 845, "type": "communication", "en": "this is critical", "hy": ["սա կրիտիկական է"] },
  { "id": 846, "type": "communication", "en": "this is urgent", "hy": ["սա շտապ է"] },
  { "id": 847, "type": "communication", "en": "please prioritize this", "hy": ["խնդրում ենք առաջնահերթ դարձնել"] },
  { "id": 848, "type": "communication", "en": "high priority issue", "hy": ["բարձր առաջնահերթության խնդիր"] },
  { "id": 849, "type": "communication", "en": "blocking issue", "hy": ["արգելափակող խնդիր"] },
  { "id": 850, "type": "communication", "en": "this blocks integration", "hy": ["սա արգելափակում է ինտեգրումը"] },

  { "id": 851, "type": "communication", "en": "integration is blocked", "hy": ["ինտեգրումը արգելափակված է"] },
  { "id": 852, "type": "communication", "en": "we cannot proceed", "hy": ["չենք կարող շարունակել"] },
  { "id": 853, "type": "communication", "en": "please unblock", "hy": ["խնդրում ենք բացել"] },
  { "id": 854, "type": "communication", "en": "once fixed we proceed", "hy": ["ուղղվելուց հետո կշարունակենք"] },
  { "id": 855, "type": "communication", "en": "we will continue testing", "hy": ["կշարունակենք թեստավորումը"] },
  { "id": 856, "type": "communication", "en": "testing in progress", "hy": ["թեստավորումը ընթացքի մեջ է"] },
  { "id": 857, "type": "communication", "en": "testing completed", "hy": ["թեստավորումը ավարտված է"] },
  { "id": 858, "type": "communication", "en": "tests passed", "hy": ["թեստերը անցել են"] },
  { "id": 859, "type": "communication", "en": "tests failed", "hy": ["թեստերը ձախողվել են"] },
  { "id": 860, "type": "communication", "en": "please rerun tests", "hy": ["խնդրում ենք կրկին անցկացնել թեստերը"] },

  { "id": 861, "type": "communication", "en": "validator tests", "hy": ["վալիդատոր թեստեր"] },
  { "id": 862, "type": "communication", "en": "manual testing", "hy": ["ձեռքով թեստավորում"] },
  { "id": 863, "type": "communication", "en": "QA team", "hy": ["QA թիմ"] },
  { "id": 864, "type": "communication", "en": "QA feedback", "hy": ["QA արձագանք"] },
  { "id": 865, "type": "communication", "en": "QA approval", "hy": ["QA հաստատում"] },
  { "id": 866, "type": "communication", "en": "ready for QA", "hy": ["պատրաստ QA-ի համար"] },
  { "id": 867, "type": "communication", "en": "tech ready", "hy": ["տեխնիկապես պատրաստ"] },
  { "id": 868, "type": "communication", "en": "ready for release", "hy": ["պատրաստ թողարկման համար"] },
  { "id": 869, "type": "communication", "en": "go live", "hy": ["գործարկում"] },
  { "id": 870, "type": "communication", "en": "ready to go live", "hy": ["պատրաստ է գործարկման"] },

  { "id": 871, "type": "communication", "en": "please share credentials", "hy": ["խնդրում ենք տրամադրել տվյալները"] },
  { "id": 872, "type": "communication", "en": "please share access", "hy": ["խնդրում ենք տրամադրել մուտք"] },
  { "id": 873, "type": "communication", "en": "please provide IPs", "hy": ["խնդրում ենք տրամադրել IP-ները"] },
  { "id": 874, "type": "communication", "en": "IP whitelist", "hy": ["IP whitelist"] },
  { "id": 875, "type": "communication", "en": "please whitelist our IP", "hy": ["խնդրում ենք whitelist անել մեր IP"] },
  { "id": 876, "type": "communication", "en": "IP not whitelisted", "hy": ["IP whitelist-ում չկա"] },
  { "id": 877, "type": "communication", "en": "access is blocked", "hy": ["մուտքը արգելափակված է"] },
  { "id": 878, "type": "communication", "en": "access granted", "hy": ["մուտքը տրամադրված է"] },
  { "id": 879, "type": "communication", "en": "credentials are valid", "hy": ["տվյալները վավեր են"] },
  { "id": 880, "type": "communication", "en": "credentials not working", "hy": ["տվյալները չեն աշխատում"] },

  { "id": 881, "type": "communication", "en": "please check logs", "hy": ["խնդրում ենք ստուգել լոգերը"] },
  { "id": 882, "type": "communication", "en": "see attached logs", "hy": ["տես կցված լոգերը"] },
  { "id": 883, "type": "communication", "en": "attached screenshot", "hy": ["կցված է սքրինշոթ"] },
  { "id": 884, "type": "communication", "en": "see screenshot", "hy": ["տես սքրինշոթ"] },
  { "id": 885, "type": "communication", "en": "sharing example", "hy": ["կիսվում եմ օրինակով"] },
  { "id": 886, "type": "communication", "en": "please find attached", "hy": ["կցված է"] },
  { "id": 887, "type": "communication", "en": "for reference", "hy": ["տեղեկանքի համար"] },
  { "id": 888, "type": "communication", "en": "example below", "hy": ["օրինակը ստորև"] },
  { "id": 889, "type": "communication", "en": "as you can see", "hy": ["ինչպես տեսնում եք"] },
  { "id": 890, "type": "communication", "en": "please note", "hy": ["խնդրում ենք ուշադրություն դարձնել"] },

  { "id": 891, "type": "communication", "en": "important note", "hy": ["կարևոր նշում"] },
  { "id": 892, "type": "communication", "en": "please be aware", "hy": ["խնդրում ենք ուշադրություն դարձնել"] },
  { "id": 893, "type": "communication", "en": "as per documentation", "hy": ["համաձայն փաստաթղթի"] },
  { "id": 894, "type": "communication", "en": "according to docs", "hy": ["համաձայն դոկումենտացիայի"] },
  { "id": 895, "type": "communication", "en": "please follow docs", "hy": ["խնդրում ենք հետևել դոկումենտացիային"] },
  { "id": 896, "type": "communication", "en": "documentation updated", "hy": ["դոկումենտացիան թարմացված է"] },
  { "id": 897, "type": "communication", "en": "docs outdated", "hy": ["դոկումենտացիան հնացած է"] },
  { "id": 898, "type": "communication", "en": "please update docs", "hy": ["խնդրում ենք թարմացնել դոկումենտացիան"] },
  { "id": 899, "type": "communication", "en": "everything is clear", "hy": ["ամեն ինչ պարզ է"] },
  { "id": 900, "type": "communication", "en": "any questions", "hy": ["կա հարցեր"] },
  { "id": 901, "type": "communication", "en": "let's align", "hy": ["եկեք համաձայնեցնենք"] },
  { "id": 902, "type": "communication", "en": "alignment", "hy": ["համաձայնեցում"] },
  { "id": 903, "type": "communication", "en": "common understanding", "hy": ["ընդհանուր հասկացողություն"] },
  { "id": 904, "type": "communication", "en": "shared goal", "hy": ["ընդհանուր նպատակ"] },
  { "id": 905, "type": "communication", "en": "business need", "hy": ["բիզնես պահանջ"] },
  { "id": 906, "type": "communication", "en": "business impact", "hy": ["բիզնես ազդեցություն"] },
  { "id": 907, "type": "communication", "en": "customer impact", "hy": ["հաճախորդի վրա ազդեցություն"] },
  { "id": 908, "type": "communication", "en": "user impact", "hy": ["օգտատիրոջ վրա ազդեցություն"] },
  { "id": 909, "type": "communication", "en": "technical impact", "hy": ["տեխնիկական ազդեցություն"] },
  { "id": 910, "type": "communication", "en": "expected impact", "hy": ["սպասվող ազդեցություն"] },

  { "id": 911, "type": "communication", "en": "main concern", "hy": ["հիմնական մտահոգություն"] },
  { "id": 912, "type": "communication", "en": "concern", "hy": ["մտահոգություն"] },
  { "id": 913, "type": "communication", "en": "limitation", "hy": ["սահմանափակում"] },
  { "id": 914, "type": "communication", "en": "constraint", "hy": ["սահմանափակում"] },
  { "id": 915, "type": "communication", "en": "dependency", "hy": ["կախվածություն"] },
  { "id": 916, "type": "communication", "en": "blocker", "hy": ["արգելափակող խնդիր"] },
  { "id": 917, "type": "communication", "en": "escalation", "hy": ["էսկալացիա"] },
  { "id": 918, "type": "communication", "en": "escalate", "hy": ["էսկալացնել"] },
  { "id": 919, "type": "communication", "en": "urgent escalation", "hy": ["շտապ էսկալացիա"] },
  { "id": 920, "type": "communication", "en": "internal escalation", "hy": ["ներքին էսկալացիա"] },

  { "id": 921, "type": "communication", "en": "we need your support", "hy": ["մեզ պետք է ձեր աջակցությունը"] },
  { "id": 922, "type": "communication", "en": "need your assistance", "hy": ["պետք է ձեր օգնությունը"] },
  { "id": 923, "type": "communication", "en": "please assist", "hy": ["խնդրում ենք աջակցել"] },
  { "id": 924, "type": "communication", "en": "please advise", "hy": ["խնդրում ենք խորհուրդ տալ"] },
  { "id": 925, "type": "communication", "en": "your input is needed", "hy": ["ձեր կարծիքը անհրաժեշտ է"] },
  { "id": 926, "type": "communication", "en": "need your confirmation", "hy": ["պետք է ձեր հաստատումը"] },
  { "id": 927, "type": "communication", "en": "need your approval", "hy": ["պետք է ձեր հաստատումը"] },
  { "id": 928, "type": "communication", "en": "please approve", "hy": ["խնդրում ենք հաստատել"] },
  { "id": 929, "type": "communication", "en": "please confirm the plan", "hy": ["խնդրում ենք հաստատել պլանը"] },
  { "id": 930, "type": "communication", "en": "please confirm the timeline", "hy": ["խնդրում ենք հաստատել ժամանակացույցը"] },

  { "id": 931, "type": "communication", "en": "proposed solution", "hy": ["առաջարկվող լուծում"] },
  { "id": 932, "type": "communication", "en": "suggested approach", "hy": ["առաջարկվող մոտեցում"] },
  { "id": 933, "type": "communication", "en": "recommended action", "hy": ["խորհուրդ տրվող գործողություն"] },
  { "id": 934, "type": "communication", "en": "next action", "hy": ["հաջորդ գործողություն"] },
  { "id": 935, "type": "communication", "en": "action item", "hy": ["գործողության կետ"] },
  { "id": 936, "type": "communication", "en": "owner", "hy": ["պատասխանատու"] },
  { "id": 937, "type": "communication", "en": "responsible person", "hy": ["պատասխանատու անձ"] },
  { "id": 938, "type": "communication", "en": "point of contact", "hy": ["կոնտակտային անձ"] },
  { "id": 939, "type": "communication", "en": "stakeholder", "hy": ["շահագրգիռ կողմ"] },
  { "id": 940, "type": "communication", "en": "decision maker", "hy": ["որոշում կայացնող"] },

  { "id": 941, "type": "communication", "en": "we suggest", "hy": ["մենք առաջարկում ենք"] },
  { "id": 942, "type": "communication", "en": "we recommend", "hy": ["մենք խորհուրդ ենք տալիս"] },
  { "id": 943, "type": "communication", "en": "we propose", "hy": ["մենք առաջարկում ենք"] },
  { "id": 944, "type": "communication", "en": "we prefer", "hy": ["մենք նախընտրում ենք"] },
  { "id": 945, "type": "communication", "en": "we expect", "hy": ["մենք ակնկալում ենք"] },
  { "id": 946, "type": "communication", "en": "we require", "hy": ["մենք պահանջում ենք"] },
  { "id": 947, "type": "communication", "en": "we need to proceed", "hy": ["պետք է շարունակենք"] },
  { "id": 948, "type": "communication", "en": "we need to decide", "hy": ["պետք է որոշենք"] },
  { "id": 949, "type": "communication", "en": "we need to align", "hy": ["պետք է համաձայնեցնենք"] },
  { "id": 950, "type": "communication", "en": "we need to prioritize", "hy": ["պետք է առաջնահերթություն տանք"] },

  { "id": 951, "type": "communication", "en": "please treat this as priority", "hy": ["խնդրում ենք սա դիտարկել որպես առաջնահերթություն"] },
  { "id": 952, "type": "communication", "en": "please handle this urgently", "hy": ["խնդրում ենք շտապ զբաղվել սրանով"] },
  { "id": 953, "type": "communication", "en": "this requires immediate attention", "hy": ["սա պահանջում է անհապաղ ուշադրություն"] },
  { "id": 954, "type": "communication", "en": "this is blocking go live", "hy": ["սա արգելափակում է գործարկումը"] },
  { "id": 955, "type": "communication", "en": "this is blocking testing", "hy": ["սա արգելափակում է թեստավորումը"] },
  { "id": 956, "type": "communication", "en": "this affects production", "hy": ["սա ազդում է արտադրական միջավայրի վրա"] },
  { "id": 957, "type": "communication", "en": "this affects users", "hy": ["սա ազդում է օգտատերերի վրա"] },
  { "id": 958, "type": "communication", "en": "this may cause issues", "hy": ["սա կարող է խնդիրներ առաջացնել"] },
  { "id": 959, "type": "communication", "en": "this may impact release", "hy": ["սա կարող է ազդել թողարկման վրա"] },
  { "id": 960, "type": "communication", "en": "this must be fixed before release", "hy": ["սա պետք է ուղղվի մինչև թողարկումը"] },

  { "id": 961, "type": "communication", "en": "to avoid delays", "hy": ["ուշացումներից խուսափելու համար"] },
  { "id": 962, "type": "communication", "en": "to avoid issues", "hy": ["խնդիրներից խուսափելու համար"] },
  { "id": 963, "type": "communication", "en": "to proceed further", "hy": ["ավելի առաջ շարունակելու համար"] },
  { "id": 964, "type": "communication", "en": "before we proceed", "hy": ["մինչև շարունակելը"] },
  { "id": 965, "type": "communication", "en": "before go live", "hy": ["գործարկումից առաջ"] },
  { "id": 966, "type": "communication", "en": "after confirmation", "hy": ["հաստատումից հետո"] },
  { "id": 967, "type": "communication", "en": "once approved", "hy": ["հաստատվելուց հետո"] },
  { "id": 968, "type": "communication", "en": "once completed", "hy": ["ավարտվելուց հետո"] },
  { "id": 969, "type": "communication", "en": "once resolved", "hy": ["լուծվելուց հետո"] },
  { "id": 970, "type": "communication", "en": "once tested", "hy": ["թեստավորվելուց հետո"] },

  { "id": 971, "type": "communication", "en": "we are aligned", "hy": ["մենք համաձայնեցված ենք"] },
  { "id": 972, "type": "communication", "en": "we are not aligned", "hy": ["մենք համաձայնեցված չենք"] },
  { "id": 973, "type": "communication", "en": "let's discuss internally", "hy": ["եկեք քննարկենք ներսում"] },
  { "id": 974, "type": "communication", "en": "we will discuss internally", "hy": ["կքննարկենք ներսում"] },
  { "id": 975, "type": "communication", "en": "internal discussion", "hy": ["ներքին քննարկում"] },
  { "id": 976, "type": "communication", "en": "external discussion", "hy": ["արտաքին քննարկում"] },
  { "id": 977, "type": "communication", "en": "partner feedback", "hy": ["գործընկերոջ արձագանք"] },
  { "id": 978, "type": "communication", "en": "provider feedback", "hy": ["պրովայդերի արձագանք"] },
  { "id": 979, "type": "communication", "en": "operator feedback", "hy": ["օպերատորի արձագանք"] },
  { "id": 980, "type": "communication", "en": "management approval", "hy": ["ղեկավարության հաստատում"] },

  { "id": 981, "type": "communication", "en": "final approval", "hy": ["վերջնական հաստատում"] },
  { "id": 982, "type": "communication", "en": "final confirmation", "hy": ["վերջնական հաստատում"] },
  { "id": 983, "type": "communication", "en": "final decision", "hy": ["վերջնական որոշում"] },
  { "id": 984, "type": "communication", "en": "final check", "hy": ["վերջնական ստուգում"] },
  { "id": 985, "type": "communication", "en": "final review", "hy": ["վերջնական վերանայում"] },
  { "id": 986, "type": "communication", "en": "final testing", "hy": ["վերջնական թեստավորում"] },
  { "id": 987, "type": "communication", "en": "final result", "hy": ["վերջնական արդյունք"] },
  { "id": 988, "type": "communication", "en": "final update", "hy": ["վերջնական թարմացում"] },
  { "id": 989, "type": "communication", "en": "final status", "hy": ["վերջնական կարգավիճակ"] },
  { "id": 990, "type": "communication", "en": "final note", "hy": ["վերջնական նշում"] },

  { "id": 991, "type": "communication", "en": "let's close this", "hy": ["եկեք փակենք սա"] },
  { "id": 992, "type": "communication", "en": "we can close this", "hy": ["կարող ենք փակել սա"] },
  { "id": 993, "type": "communication", "en": "nothing else from our side", "hy": ["մեր կողմից այլ բան չկա"] },
  { "id": 994, "type": "communication", "en": "all clear from our side", "hy": ["մեր կողմից ամեն ինչ պարզ է"] },
  { "id": 995, "type": "communication", "en": "we are good to proceed", "hy": ["կարող ենք շարունակել"] },
  { "id": 996, "type": "communication", "en": "ready to proceed", "hy": ["պատրաստ ենք շարունակել"] },
  { "id": 997, "type": "communication", "en": "ready for next step", "hy": ["պատրաստ ենք հաջորդ քայլին"] },
  { "id": 998, "type": "communication", "en": "thanks everyone", "hy": ["շնորհակալություն բոլորին"] },
  { "id": 999, "type": "communication", "en": "have a good day", "hy": ["լավ օր մաղթում եմ"] },
  { "id": 1000, "type": "communication", "en": "best regards", "hy": ["հարգանքով"] }




];

module.exports = words;
